// quiz-data.js - クイズデータ（小2〜小6対応・学年1位レベル）
const QUIZ_DATA = {
  math: {
    name: 'さんすうの どうくつ',
    color: '#FF6600',
    portalColor: 0xFF6600,
    grades: {
      grade2: [
        { q: '32 + 15 = ?', opts: ['47','45','57','43'], correct: 0, hint: 'じゅうのくらいと いちのくらいに わけよう！', explain: '32+15=47' },
        { q: '21 + 36 = ?', opts: ['57','55','67','53'], correct: 0, hint: 'くらいごとに たそう！', explain: '21+36=57' },
        { q: '48 + 23 = ?', opts: ['61','71','68','65'], correct: 1, hint: 'くりあがりに ちゅうい！', explain: '48+23=71（8+3=11 くりあがり）' },
        { q: '75 - 32 = ?', opts: ['43','33','47','41'], correct: 0, hint: 'くらいごとに ひこう！', explain: '75-32=43' },
        { q: '53 - 28 = ?', opts: ['25','35','23','27'], correct: 0, hint: 'くりさがりに ちゅうい！', explain: '53-28=25' },
        { q: '2 × 3 = ?', opts: ['5','6','8','4'], correct: 1, hint: 'に さん は？', explain: '2×3=6（に さん が ろく）' },
        { q: '3 × 4 = ?', opts: ['7','10','12','9'], correct: 2, hint: 'さん し は？', explain: '3×4=12（さん し じゅうに）' },
        { q: '5 × 6 = ?', opts: ['25','30','35','28'], correct: 1, hint: 'ご ろく は？', explain: '5×6=30（ご ろく さんじゅう）' },
        { q: '4 × 7 = ?', opts: ['24','28','32','21'], correct: 1, hint: 'し しち は？', explain: '4×7=28（し しち にじゅうはち）' },
        { q: '8 × 9 = ?', opts: ['63','72','81','64'], correct: 1, hint: 'はち く は？', explain: '8×9=72（はち く しちじゅうに）' },
        { q: '1時間 = なん分？', opts: ['30分','50分','60分','100分'], correct: 2, hint: '時計が 1周で！', explain: '1時間=60分' },
        { q: '1cm = なんmm？', opts: ['5mm','10mm','20mm','100mm'], correct: 1, hint: '10のメモリで 1cm！', explain: '1cm=10mm' },
        { q: '三角形の 辺の数は？', opts: ['2ほん','3ほん','4ほん','5ほん'], correct: 1, hint: '「三」が ついてるよ！', explain: '三角形は辺が3本' },
        { q: '100円玉が 3まい で いくら？', opts: ['200円','300円','400円','30円'], correct: 1, hint: '100+100+100=?', explain: '100×3=300円' },
        { q: '正方形の 辺の数は？', opts: ['3ほん','4ほん','5ほん','6ほん'], correct: 1, hint: '4つの かどが あるよ！', explain: '正方形は辺が4本すべて同じ長さ' },
        { type:'truefalse', q:'5 × 8 = 40　ただしい？', opts:['○','×'], correct:0, hint:'ご は ？', explain:'5×8=40（ご は しじゅう）せいかい！' },
        { type:'truefalse', q:'70 + 40 = 100　ただしい？', opts:['○','×'], correct:1, hint:'70と40を たしてみよう', explain:'70+40=110 です' },
        { type:'truefalse', q:'三角形の かどの 数は 3つ　ただしい？', opts:['○','×'], correct:0, hint:'三角形の「三」！', explain:'三角形はかど（頂点）が3つ せいかい！' },
        { type:'keypad', q:'8 × 7 = ?', answer:'56', explain:'8×7=56（はち しち ごじゅうろく）' },
        { type:'keypad', q:'36 + 47 = ?', answer:'83', explain:'36+47=83（くりあがりあり）' },
        { type:'keypad', q:'100 - 38 = ?', answer:'62', explain:'100-38=62' },
        { type:'keypad', q:'9 × 6 = ?', answer:'54', explain:'9×6=54（く ろく ごじゅうし）' },
      ],
      grade3: [
        { q: '125 + 68 = ?', opts: ['183','193','203','173'], correct: 1, hint: 'くりあがりに ちゅうい！', explain: '125+68=193' },
        { q: '500 - 237 = ?', opts: ['273','263','363','253'], correct: 1, hint: 'ゼロから ひくよ！', explain: '500-237=263' },
        { q: '12 ÷ 4 = ?', opts: ['2','3','4','5'], correct: 1, hint: '4のだんで 考えよう！', explain: '12÷4=3（4×3=12）' },
        { q: '24 ÷ 6 = ?', opts: ['3','4','5','6'], correct: 1, hint: '6のだんで 確認！', explain: '24÷6=4（6×4=24）' },
        { q: '7 × 8 = ?', opts: ['54','56','58','48'], correct: 1, hint: 'しち は ？', explain: '7×8=56（しち は ごじゅうろく）' },
        { q: '6 × 9 = ?', opts: ['45','54','56','63'], correct: 1, hint: 'ろく く ？', explain: '6×9=54（ろく く ごじゅうし）' },
        { q: '0.3 + 0.5 = ?', opts: ['0.7','0.8','1.0','0.9'], correct: 1, hint: '小数点を そろえよう！', explain: '0.3+0.5=0.8' },
        { q: '1m = なんcm？', opts: ['10cm','100cm','1000cm','50cm'], correct: 1, hint: 'メートルより 小さい 単位！', explain: '1m=100cm' },
        { q: '1L = なんmL？', opts: ['10mL','100mL','500mL','1000mL'], correct: 3, hint: 'ポーション なんこぶん？', explain: '1L=1000mL' },
        { q: '縦4cm 横6cmの 長方形の 面積は？', opts: ['10cm²','20cm²','24cm²','40cm²'], correct: 2, hint: 'たて × よこ！', explain: '面積=4×6=24cm²' },
        { q: '56 ÷ 7 = ?', opts: ['6','7','8','9'], correct: 2, hint: '7のだんで 考えよう！', explain: '56÷7=8（7×8=56）' },
        { q: '1kg = なんg？', opts: ['10g','100g','1000g','10000g'], correct: 2, hint: 'kは1000のことだよ！', explain: '1kg=1000g' },
        { type:'truefalse', q:'1km = 1000m　ただしい？', opts:['○','×'], correct:0, hint:'k（キロ）は1000のこと！', explain:'1km=1000m せいかい！' },
        { type:'truefalse', q:'三角形の 内角の和は 360度　ただしい？', opts:['○','×'], correct:1, hint:'三角形と 四角形は ちがうよ', explain:'三角形の内角の和は180度です' },
        { type:'keypad', q:'63 ÷ 9 = ?', answer:'7', explain:'63÷9=7（9×7=63）' },
        { type:'keypad', q:'48 ÷ 6 = ?', answer:'8', explain:'48÷6=8（6×8=48）' },
        { type:'keypad', q:'27 × 4 = ?', answer:'108', explain:'27×4=108' },
      ],
      grade4: [
        { q: '1/2 + 1/4 = ?', opts: ['2/6','3/4','1/4','2/4'], correct: 1, hint: '分母を 合わせよう！', explain: '1/2=2/4、2/4+1/4=3/4' },
        { q: '3/4 - 1/8 = ?', opts: ['2/4','5/8','4/8','2/8'], correct: 1, hint: '3/4を 8分の？に 直そう！', explain: '3/4=6/8、6/8-1/8=5/8' },
        { q: '3/6 を 約分すると？', opts: ['1/2','1/3','2/3','3/3'], correct: 0, hint: '分子と 分母を 3で わろう！', explain: '3÷3=1、6÷3=2 → 1/2' },
        { q: '2.5 × 4 = ?', opts: ['8','9','10','11'], correct: 2, hint: '2.5=2+0.5に 分けよう！', explain: '2×4+0.5×4=8+2=10' },
        { q: '縦5cm 横8cmの 長方形の 面積は？', opts: ['13cm²','26cm²','40cm²','56cm²'], correct: 2, hint: 'たて × よこ！', explain: '面積=5×8=40cm²' },
        { q: '底辺8cm 高さ5cmの 三角形の 面積は？', opts: ['13cm²','20cm²','40cm²','80cm²'], correct: 1, hint: '底辺 × 高さ ÷ 2！', explain: '8×5÷2=20cm²' },
        { q: '直角は 何度？', opts: ['45度','90度','180度','360度'], correct: 1, hint: 'L字型の かど！', explain: '直角=90度' },
        { q: '三角形の 内角の和は？', opts: ['90度','180度','270度','360度'], correct: 1, hint: '3つのかどを 全部たすと？', explain: '三角形の内角の和=180度' },
        { q: '1億は 何万？', opts: ['100万','1000万','10000万','100000万'], correct: 2, hint: '0の 数を 数えよう！', explain: '1億=10000万' },
        { q: '4850を 百の位で 四捨五入すると？', opts: ['4000','4800','5000','4900'], correct: 2, hint: '百の位の数(8)は 5以上？', explain: '百の位が8（≧5）なので切り上げ → 5000' },
        { q: '84の 約数でないものは？', opts: ['4','6','7','5'], correct: 3, hint: '84÷5は 割り切れる？', explain: '84÷5=16余り4なので5は約数でない' },
        { q: '角柱の 底面は 何個？', opts: ['1個','2個','3個','4個'], correct: 1, hint: '上と 下に あるよ！', explain: '角柱は底面が2個（上面・下面）' },
        { type:'truefalse', q:'直角は 90度　ただしい？', opts:['○','×'], correct:0, hint:'L字型の かど！', explain:'直角=90度 せいかい！' },
        { type:'truefalse', q:'四角形の 内角の和は 270度　ただしい？', opts:['○','×'], correct:1, hint:'三角形×2で 考えよう', explain:'四角形の内角の和は360度です' },
        { type:'keypad', q:'縦6cm 横9cmの 長方形の 面積は？ (cm²)', answer:'54', explain:'6×9=54cm²（たて×よこ）' },
        { type:'keypad', q:'底辺10cm 高さ6cmの 三角形の 面積は？ (cm²)', answer:'30', explain:'10×6÷2=30cm²' },
      ],
      grade5: [
        { q: '2/3 × 3/4 = ?', opts: ['5/7','1/2','6/12','2/4'], correct: 1, hint: '分子どうし、分母どうし かけよう！', explain: '2×3=6、3×4=12 → 6/12=1/2' },
        { q: '3/4 ÷ 3/8 = ?', opts: ['9/32','1','2','3/2'], correct: 2, hint: '÷は 逆数を かける！', explain: '3/4 × 8/3 = 24/12 = 2' },
        { q: '0.6 × 1.5 = ?', opts: ['0.7','0.9','1.0','1.8'], correct: 1, hint: '6×15=90、小数点を 2つ 左へ！', explain: '0.6×1.5=0.90=0.9' },
        { q: '半径5cmの 円の 面積は？（π=3.14）', opts: ['15.7cm²','31.4cm²','78.5cm²','157cm²'], correct: 2, hint: '面積=半径×半径×π！', explain: '5×5×3.14=78.5cm²' },
        { q: '縦3cm 横4cm 高さ5cmの 直方体の 体積は？', opts: ['12cm³','60cm³','120cm³','24cm³'], correct: 1, hint: 'たて×よこ×たかさ！', explain: '3×4×5=60cm³' },
        { q: '4つの数 10,8,6,4の 平均は？', opts: ['6','7','8','9'], correct: 1, hint: '全部たして 個数で わる！', explain: '(10+8+6+4)÷4=28÷4=7' },
        { q: '時速60kmで 2時間 走ると 何km？', opts: ['30km','60km','120km','180km'], correct: 2, hint: '速さ×時間=距離！', explain: '60×2=120km' },
        { q: '30の 20% は？', opts: ['6','10','12','15'], correct: 0, hint: '30×0.2=?', explain: '30×20÷100=30×0.2=6' },
        { q: '公倍数：4と6の 最小公倍数は？', opts: ['10','12','18','24'], correct: 1, hint: '4の倍数と 6の倍数を 書いてみよう！', explain: '4の倍数:4,8,12… 6の倍数:6,12… 最小=12' },
        { q: '公約数：12と18の 最大公約数は？', opts: ['3','4','6','9'], correct: 2, hint: '12と18を 同じ数で われる 最大は？', explain: '12=2²×3、18=2×3² → GCD=2×3=6' },
        { q: '四角形の 内角の和は？', opts: ['180度','270度','360度','450度'], correct: 2, hint: '三角形を 2つに 分けると？', explain: '四角形=三角形×2 → 180×2=360度' },
        { q: '1.2 ÷ 0.4 = ?', opts: ['0.3','3','0.48','2.4'], correct: 1, hint: '両方を 10倍すると？', explain: '1.2÷0.4=12÷4=3' },
        { type:'truefalse', q:'四角形の 内角の和は 360度　ただしい？', opts:['○','×'], correct:0, hint:'三角形×2！', explain:'四角形=三角形2つ分 → 180×2=360度 せいかい！' },
        { type:'truefalse', q:'時速60kmで 3時間 走ると 150km　ただしい？', opts:['○','×'], correct:1, hint:'速さ×時間=距離', explain:'60×3=180km です' },
        { type:'keypad', q:'時速50kmで 3時間 走ると 何km？', answer:'150', explain:'50×3=150km（速さ×時間）' },
        { type:'keypad', q:'半径4cmの 円の 面積は？\n（π=3.14、答えは整数部分のみ）', answer:'50', explain:'4×4×3.14=50.24 ≒ 50cm²' },
      ],
      grade6: [
        { q: '2 : 3 = 4 : ?', opts: ['5','6','8','9'], correct: 1, hint: '比の 内項の積=外項の積！', explain: '2×?=3×4=12 → ?=6' },
        { q: 'xがyに 正比例するとき x=2でy=6。x=5のとき y=?', opts: ['10','12','15','18'], correct: 2, hint: 'y=kx の kを 求めよう！', explain: 'k=6÷2=3 → y=3×5=15' },
        { q: '底面積10cm² 高さ6cmの 角柱の 体積は？', opts: ['16cm³','60cm³','160cm³','600cm³'], correct: 1, hint: '体積=底面積×高さ！', explain: '10×6=60cm³' },
        { q: '速さ120km/h 距離360kmを 走る 時間は？', opts: ['2時間','3時間','4時間','5時間'], correct: 1, hint: '時間=距離÷速さ！', explain: '360÷120=3時間' },
        { q: '全体のうち 75%が 90人。 全体は 何人？', opts: ['67人','100人','120人','135人'], correct: 2, hint: '全体×0.75=90 → 全体=?', explain: '90÷0.75=120人' },
        { q: 'n角形の 内角の和の 公式は？', opts: ['90(n-1)°','180(n-2)°','180(n-1)°','360°'], correct: 1, hint: '三角形=180°、四角形=360°…', explain: 'n角形の内角の和=180°×(n-2)' },
        { q: '1000mL = 何dL？', opts: ['1dL','10dL','100dL','1000dL'], correct: 1, hint: '1dL=100mL！', explain: '1000mL÷100=10dL' },
        { q: '仕事全体を1とする。Aが1/3日でできる。3日でいくつ？', opts: ['1','3','1/3','1/9'], correct: 0, hint: '1日に1/3できるなら 3日では？', explain: '1/3×3=1（全体完成）' },
        { q: '縮尺1/25000の 地図で 4cmは 実際 何km？', opts: ['0.1km','1km','4km','100km'], correct: 1, hint: '4cm×25000=?cm を kmに！', explain: '4×25000=100000cm=1000m=1km' },
        { q: '次のうち 素数は どれ？', opts: ['1','4','9','11'], correct: 3, hint: '1と自分だけで わり切れる数！', explain: '1は素数でない。11=11×1のみ → 素数' },
        { q: 'π=3.14 として 直径10cmの 円周は？', opts: ['15.7cm','31.4cm','78.5cm','100cm'], correct: 1, hint: '円周=直径×π！', explain: '10×3.14=31.4cm' },
        { q: '42を 素因数分解すると？', opts: ['2×21','2×3×7','3×14','6×7'], correct: 1, hint: '小さい 素数から わっていこう！', explain: '42÷2=21、21÷3=7 → 2×3×7' },
      ],
    }
  },
  japanese: {
    name: 'こくごの もり',
    color: '#00CC44',
    portalColor: 0x00CC44,
    grades: {
      grade2: [
        { q: '「花」の よみかたは？', opts: ['き','はな','くさ','は'], correct: 1, hint: 'きれいに さくよ！', explain: '「花」→ はな' },
        { q: '「空」の よみかたは？', opts: ['うみ','そら','やま','かわ'], correct: 1, hint: '雲が うかんでる！', explain: '「空」→ そら' },
        { q: '「石」の よみかたは？', opts: ['つち','いし','かわ','ほし'], correct: 1, hint: 'マイクラで ほれるよ！', explain: '「石」→ いし' },
        { q: '「大きい」の はんたいは？', opts: ['ひくい','ちいさい','ながい','みじかい'], correct: 1, hint: 'クリーパーは大きい、こうもりは？', explain: '「大きい」の反対は「小さい」' },
        { q: '「走る・歩く・泳ぐ」の なかまは？', opts: ['りんご','飛ぶ','赤い','きれい'], correct: 1, hint: 'からだを 動かす ことば！', explain: '走る・歩く・泳ぐ・飛ぶ はどれも動作（動詞）' },
        { q: '「とても」と 同じような 意味の ことばは？', opts: ['すこし','たいへん','あまり','ちょっと'], correct: 1, hint: 'おなじ 意味の ことば！', explain: '「とても」≒「たいへん」' },
        { q: '「犬」と「猫」、五十音で 先に くるのは？', opts: ['犬（い）','猫（ね）','同じ','わからない'], correct: 0, hint: '「い」と「ね」どちらが先？', explain: '五十音順では「い」が「ね」より先に来る' },
        { q: '「山」の よみかたは？', opts: ['かわ','うみ','やま','たに'], correct: 2, hint: 'マイクラで のぼれるよ！', explain: '「山」→ やま' },
        { q: '「明るい」の はんたいは？', opts: ['せまい','くらい','ひくい','よわい'], correct: 1, hint: 'ナイトモードは？', explain: '「明るい」の反対は「暗い（くらい）」' },
        { type:'truefalse', q:'「火曜日」の よみかたは「かようび」　ただしい？', opts:['○','×'], correct:0, hint:'曜日の よみかた！', explain:'「火曜日」→ かようび せいかい！' },
        { type:'truefalse', q:'「雨」の よみかたは「かみなり」　ただしい？', opts:['○','×'], correct:1, hint:'空から ふってくる もの！', explain:'「雨」→ あめ です' },
        { type:'truefalse', q:'「大きい」と「小さい」は はんたい語　ただしい？', opts:['○','×'], correct:0, hint:'反対の 意味の ことば！', explain:'「大きい」↔「小さい」は反対語 せいかい！' },
      ],
      grade3: [
        { q: '「春」の よみかたは？', opts: ['なつ','はる','あき','ふゆ'], correct: 1, hint: 'さくらが さく きせつ！', explain: '「春」→ はる。春夏秋冬の最初。' },
        { q: '「海」の よみかたは？', opts: ['やま','かわ','うみ','もり'], correct: 2, hint: 'さかなが いる ひろいところ！', explain: '「海」→ うみ' },
        { q: '「森」は なにが たくさん？', opts: ['みず','き','いし','はな'], correct: 1, hint: '「木」が 3つ あるよ！', explain: '「森」という字は木が3つ。木がたくさんある場所。' },
        { q: '「走る」は なに？', opts: ['名詞','動詞','形容詞','接続詞'], correct: 1, hint: 'からだを うごかす ことば！', explain: '「走る」は動作を表す動詞' },
        { q: '「美しい」は なに？', opts: ['名詞','動詞','形容詞','接続詞'], correct: 2, hint: 'ようすを あらわすよ！', explain: '「美しい」はようす（状態）を表す形容詞' },
        { q: '「ねこの手も かりたい」の いみは？', opts: ['ねこが すき','とても いそがしい','ねこの あし','てが ちいさい'], correct: 1, hint: '「ねこの ても かりたい！」', explain: '「猫の手も借りたい」=とても忙しいことわざ' },
        { q: '「光」の よみかたは？', opts: ['かぜ','ひかり','おと','いろ'], correct: 1, hint: 'グロウストーンの ○○○！', explain: '「光」→ ひかり' },
        { q: '「友」の よみかたは？', opts: ['あに','いもうと','とも','おや'], correct: 2, hint: 'いっしょに あそぶ ひと！', explain: '「友」→ とも。友達。' },
        { q: '「星」の よみかたは？', opts: ['ほし','つき','そら','くも'], correct: 0, hint: 'よるに キラキラ ひかるよ！', explain: '「星」→ ほし' },
        { q: '「急いで」の 使い方で 正しいのは？', opts: ['急いで かんがえる','急いで ねる','急いで かける','急いで まつ'], correct: 2, hint: '「急いで」は 速く動くとき！', explain: '急いでかける＝急いで走る。急いで待つ・寝るは矛盾する' },
        { type:'truefalse', q:'「走る」は 動詞である　ただしい？', opts:['○','×'], correct:0, hint:'からだを 動かす ことば！', explain:'「走る」は動作を表す動詞 せいかい！' },
        { type:'truefalse', q:'「美しい」は 名詞である　ただしい？', opts:['○','×'], correct:1, hint:'ようすを あらわす ことば？', explain:'「美しい」はようすを表す形容詞です' },
        { type:'truefalse', q:'「猫の手も借りたい」は とても いそがしい という 意味　ただしい？', opts:['○','×'], correct:0, hint:'ことわざ！', explain:'「猫の手も借りたい」=とても忙しい せいかい！' },
      ],
      grade4: [
        { q: '「季節」の読み方は？', opts: ['きせつ','きぶん','けしき','かんせつ'], correct: 0, hint: '春・夏・秋・冬のこと！', explain: '「季節」→ きせつ' },
        { q: '「観察」の読み方は？', opts: ['かんさつ','かんしょう','かんそう','かんけい'], correct: 0, hint: 'じっくり 見ること！', explain: '「観察」→ かんさつ' },
        { q: '「類義語」の 意味は？', opts: ['反対の意味の語','似た意味の語','同じ読みの語','別の品詞'], correct: 1, hint: '「うれしい」と「よろこぶ」は？', explain: '類義語=似た意味を持つ言葉' },
        { q: '漢字の「部首」の 役割は？', opts: ['意味のヒント','読み方を決める','書き順を示す','画数を増やす'], correct: 0, hint: '「水」偏は 水に 関係！', explain: '部首は漢字の意味の分類や意味のヒントになる' },
        { q: '「文章の主語」とは？', opts: ['動作の内容','何が・誰がにあたる部分','時間を表す','場所を表す'], correct: 1, hint: '「〇〇が（は）～する」の〇〇！', explain: '主語=「何が/誰が」に当たる文の主役部分' },
        { q: '「接続詞」の 例は？', opts: ['走る','きれい','しかし','ねこ'], correct: 2, hint: '文と文を つなぐ ことば！', explain: '接続詞=「しかし・だから・また・そして」など' },
        { q: '「同訓異字」の 例は？', opts: ['熱い・暑い','美しい・きれい','海・川','走る・歩く'], correct: 0, hint: '読み方が 同じで 字が 違う！', explain: '「熱い（あつい）」と「暑い（あつい）」は同訓異字' },
        { q: '日記の 書き方で 大切なのは？', opts: ['他の人のことだけ書く','その日の出来事や気持ちを書く','むずかしい言葉を使う','長くても短くてもよい'], correct: 1, hint: '自分が 体験したことを 書くよ！', explain: '日記は自分の体験・出来事・気持ちを書くもの' },
      ],
      grade5: [
        { q: '「象徴」の 読み方は？', opts: ['しょうちょう','しょうてん','さんちょう','えんちょう'], correct: 0, hint: '「シンボル」のこと！', explain: '「象徴」→ しょうちょう。何かを代表する意味' },
        { q: '「比喩」の 説明として 正しいのは？', opts: ['物事を直接説明する','物事を別のものにたとえる','反対のことを言う','音を言葉で表す'], correct: 1, hint: '「雲のような やわらかい 声」は？', explain: '比喩=ある物事を別のものにたとえる表現' },
        { q: '「尊敬語」の 例は？', opts: ['いただく','おっしゃる','参る','申す'], correct: 1, hint: '相手の 動作を 高める言葉！', explain: '「おっしゃる」は「言う」の尊敬語。「いただく」は謙譲語' },
        { q: '「謙譲語」の 例は？', opts: ['いらっしゃる','召し上がる','いただく','なさる'], correct: 2, hint: '自分を へりくだる 言葉！', explain: '「いただく」は「もらう・食べる」の謙譲語' },
        { q: '「体言止め」とは？', opts: ['動詞で文を終える','名詞で文を終える','形容詞で文を終える','助詞で文を終える'], correct: 1, hint: '「輝く 星。」のように 名詞で終わる！', explain: '体言止め=名詞（体言）で文・句を終わらせる表現技法' },
        { q: '「起承転結」の「転」は 何をする？', opts: ['話題を始める','前の内容を発展させる','内容を大きく変える','まとめる'], correct: 2, hint: '四コマ漫画の 3コマ目！', explain: '「転」=それまでの流れを転換・変化させる部分' },
        { q: '次のうち 熟語の 構成で「主語+述語」は？', opts: ['登山','読書','日没','往復'], correct: 2, hint: '「日が 没する」で 文になる！', explain: '「日没」=「日が没する」（主語+述語）' },
        { q: '「反語」の 説明は？', opts: ['反対の意味の語','疑問の形で断定する表現','二つの文をつなぐ語','音を文字で表す'], correct: 1, hint: '「そんなことが できる？（→できない）」', explain: '反語=疑問形で強く肯定/否定を表す表現' },
      ],
      grade6: [
        { q: '「竹取物語」の 主人公は？', opts: ['かぐや姫','浦島太郎','桃太郎','一寸法師'], correct: 0, hint: '竹の中から 生まれた！', explain: '「竹取物語」はかぐや姫の物語。日本最古の物語とも言われる' },
        { q: '「枕草子」を 書いたのは？', opts: ['紫式部','清少納言','与謝野晶子','樋口一葉'], correct: 1, hint: '「春は あけぼの」で 始まる！', explain: '枕草子は清少納言が書いた随筆（エッセイ）' },
        { q: '「故事成語」の「矛盾」の 意味は？', opts: ['力が強いこと','二つのことが食い違うこと','忙しいこと','早いこと'], correct: 1, hint: '何でも 突き通す矛と 何でも 防ぐ盾の 話！', explain: '矛盾=言っていることとやっていることが合わないこと' },
        { q: '「五・七・五」の リズムを 持つ 詩は？', opts: ['短歌','俳句','詩','物語'], correct: 1, hint: '季語が 必要な 詩！', explain: '俳句は五・七・五の17音で、季語を含む詩の形式' },
        { q: '「五・七・五・七・七」の リズムを 持つのは？', opts: ['俳句','詩','短歌','長歌'], correct: 2, hint: '31文字の 詩！', explain: '短歌は五・七・五・七・七の31音の詩' },
        { q: '「丁寧語」の 例は？', opts: ['おっしゃる','いただく','ございます','なさる'], correct: 2, hint: '「です・ます・ございます」は？', explain: '丁寧語=「です・ます・ございます」などで丁寧に話す表現' },
        { q: '「慣用句」の「手を焼く」の 意味は？', opts: ['料理をする','あつかいに困る','努力する','助ける'], correct: 1, hint: '扱いにくいものに 困る！', explain: '「手を焼く」=あつかいに困る・難儀する' },
        { q: '古文「あはれなり」の 現代語訳は？', opts: ['恐ろしい','おかしい','しみじみと感動的だ','明るい'], correct: 2, hint: '「あわれ（哀れ）」に 通じるよ！', explain: '「あはれなり」=しみじみとした感動・趣深い気持ち' },
      ],
    }
  },
  english: {
    name: 'えいごの むら',
    color: '#4488FF',
    portalColor: 0x4488FF,
    grades: {
      grade2: [
        { q: '「赤」は えいごで？', opts: ['Blue','Red','Green','Yellow'], correct: 1, hint: 'レッドストーンの いろ！', explain: 'Red=赤' },
        { q: '「ねこ」は えいごで？', opts: ['Dog','Cat','Pig','Bird'], correct: 1, hint: 'ニャーと なくよ！', explain: 'Cat=ねこ' },
        { q: '「おはよう」は えいごで？', opts: ['Good night','Good morning','Good bye','Hello'], correct: 1, hint: 'あさの あいさつ！', explain: 'Good morning=おはよう' },
        { q: '「1」は えいごで？', opts: ['Two','Three','One','Four'], correct: 2, hint: 'ワン！', explain: 'One=1' },
        { q: '「ありがとう」は えいごで？', opts: ['Sorry','Hello','Thank you','Please'], correct: 2, hint: 'サンキュー！', explain: 'Thank you=ありがとう' },
        { q: '「りんご」は えいごで？', opts: ['Banana','Apple','Orange','Grape'], correct: 1, hint: 'ア○○ル！', explain: 'Apple=りんご' },
        { q: '「あお」は えいごで？', opts: ['Red','Yellow','Blue','Green'], correct: 2, hint: 'ダイヤモンドの いろ！', explain: 'Blue=あお' },
        { q: '「いぬ」は えいごで？', opts: ['Cat','Dog','Pig','Cow'], correct: 1, hint: 'ワンワン！', explain: 'Dog=いぬ' },
        { q: '「10」は えいごで？', opts: ['Eight','Nine','Ten','Eleven'], correct: 2, hint: 'テン！', explain: 'Ten=10' },
        { type:'truefalse', q:'"Dog" は「いぬ」のこと　ただしい？', opts:['○','×'], correct:0, hint:'ワンワンと なくよ！', explain:'Dog=いぬ せいかい！' },
        { type:'truefalse', q:'"Cat" は「とり」のこと　ただしい？', opts:['○','×'], correct:1, hint:'ニャーと なくよ！', explain:'Cat=ねこ です' },
        { type:'truefalse', q:'"Good morning" は「おはよう」のこと　ただしい？', opts:['○','×'], correct:0, hint:'あさの あいさつ！', explain:'Good morning=おはよう せいかい！' },
      ],
      grade3: [
        { q: '「緑」は えいごで？', opts: ['Green','Blue','Brown','White'], correct: 0, hint: 'クリーパーの いろ！', explain: 'Green=緑' },
        { q: '「ぶた」は えいごで？', opts: ['Pig','Dog','Cow','Sheep'], correct: 0, hint: 'ぶひー！', explain: 'Pig=ぶた' },
        { q: '「うし」は えいごで？', opts: ['Horse','Sheep','Cow','Chicken'], correct: 2, hint: 'ミルクを くれるよ！', explain: 'Cow=うし' },
        { q: '「ひつじ」は えいごで？', opts: ['Sheep','Goat','Pig','Rabbit'], correct: 0, hint: 'ウールを くれる どうぶつ！', explain: 'Sheep=ひつじ' },
        { q: '「I like cats.」の いみは？', opts: ['ねこが すきです','ねこが います','ねこが ほしい','ねこは おおきい'], correct: 0, hint: 'like = すき！', explain: 'I like cats.=わたしはねこがすきです' },
        { q: '「How are you?」の いみは？', opts: ['あなたは だれ？','げんきですか？','なんさいですか？','どこに いますか？'], correct: 1, hint: 'あいさつの ことば！', explain: 'How are you?=元気ですか？' },
        { q: '「黄色」は えいごで？', opts: ['Orange','Gold','Yellow','White'], correct: 2, hint: 'きんの インゴットの いろ！', explain: 'Yellow=黄色' },
        { q: '「月曜日」は えいごで？', opts: ['Sunday','Saturday','Monday','Tuesday'], correct: 2, hint: 'Mo○○ay！', explain: 'Monday=月曜日' },
        { type:'truefalse', q:'"I like cats." は「ねこが いる」という意味　ただしい？', opts:['○','×'], correct:1, hint:'like = すき！', explain:'"I like cats."=わたしはねこがすきです' },
        { type:'truefalse', q:'"How are you?" は「げんきですか？」という意味　ただしい？', opts:['○','×'], correct:0, hint:'あいさつの ことば！', explain:'How are you?=元気ですか？ せいかい！' },
        { type:'truefalse', q:'"Pig" は「ひつじ」のこと　ただしい？', opts:['○','×'], correct:1, hint:'ぶひー！', explain:'Pig=ぶた、Sheep=ひつじ です' },
      ],
      grade4: [
        { q: '「This is a pen.」の 意味は？', opts: ['これはえんぴつです','これはペンです','あれはペンです','ペンが好きです'], correct: 1, hint: 'This=これ、pen=ペン！', explain: 'This is a pen.=これはペンです' },
        { q: '「I have a dog.」の 意味は？', opts: ['犬がいます','犬がすきです','わたしは犬をかっています','犬がほしいです'], correct: 2, hint: 'have=もっている・かっている', explain: 'I have a dog.=わたしは犬を飼っています' },
        { q: '「He」は だれ？', opts: ['わたし','あなた','かれ','かのじょ'], correct: 2, hint: 'She は彼女、He は？', explain: 'He=かれ She=かのじょ I=わたし You=あなた' },
        { q: '「Do you like pizza?」の 答えは？', opts: ['Yes, I am.','Yes, I do.','Yes, I have.','Yes, I like.'], correct: 1, hint: 'Do you〜?には I do！', explain: 'Do you〜?に対してYes, I do.と答える' },
        { q: '「Spring Summer Autumn Winter」は？', opts: ['曜日','つき','季節','数字'], correct: 2, hint: '春・夏・秋・冬！', explain: 'Spring=春 Summer=夏 Autumn=秋 Winter=冬（季節）' },
        { q: '「Where」は 何を 聞く 言葉？', opts: ['いつ','どこ','だれ','なに'], correct: 1, hint: '「ウェア」=「どこ」！', explain: 'Where=どこ。「Where is the school?」=学校はどこですか？' },
        { q: '「What time is it?」の 意味は？', opts: ['今日は何日？','今は何時？','どこにいますか？','天気はどう？'], correct: 1, hint: 'time=時間！', explain: 'What time is it?=今は何時ですか？' },
      ],
      grade5: [
        { q: '「I played soccer yesterday.」の 意味は？', opts: ['私はサッカーがすきです','私は昨日サッカーをしました','私はサッカーをしています','私はサッカーをします'], correct: 1, hint: 'played は play の 過去形！', explain: 'played=〜した（過去）yesterday=昨日' },
        { q: '「She can swim.」の 意味は？', opts: ['彼女は泳ぎたい','彼女は泳いでいる','彼女は泳ぐことができる','彼女は泳げない'], correct: 2, hint: 'can=〜できる！', explain: 'can=することができる。She can swim.=彼女は泳げます' },
        { q: '「I cannot run.」= 「I _____ run.」', opts: ['can\'t','don\'t','won\'t','didn\'t'], correct: 0, hint: 'cannot の 短縮形は？', explain: 'cannot=can\'t（カン\'ト）。I can\'t run.=私は走れません' },
        { q: '「He is taller than me.」の 意味は？', opts: ['彼は私より背が低い','彼は私より背が高い','私たちは同じ身長','彼は私と同じ'], correct: 1, hint: 'taller=より背が高い', explain: 'taller than=〜より背が高い（比較級）' },
        { q: '「When」は 何を 聞く 言葉？', opts: ['どこ','だれ','いつ','なに'], correct: 2, hint: '「ウェン」=「いつ」！', explain: 'When=いつ。「When is your birthday?」=誕生日はいつ？' },
        { q: '「What do you want to be?」の 意味は？', opts: ['今、何をしていますか？','何になりたいですか？','好きな食べ物は何？','何を持っていますか？'], correct: 1, hint: 'want to be=〜になりたい！', explain: 'What do you want to be?=将来何になりたいですか？' },
        { q: '英語で「月曜〜日曜」を 順に 並べると 最初は？', opts: ['Monday','Sunday','Saturday','Tuesday'], correct: 1, hint: '英語では 日曜日が 1週間の 始まり！', explain: '英語カレンダーはSunday（日）が最初。Monday〜Saturdayへ続く' },
        { q: '「I went to school.」で went は 何の 過去形？', opts: ['go','get','give','grow'], correct: 0, hint: 'go(行く)の 不規則 変化！', explain: 'go→went（不規則変化）。I went=私は行った' },
      ],
      grade6: [
        { q: '「I will go to Tokyo.」の 意味は？', opts: ['私は東京に行きました','私は東京に行きます（未来）','私は東京にいます','私は東京が好きです'], correct: 1, hint: 'will=〜するつもりだ（未来）！', explain: 'will=未来形。I will go=私は行くつもりです' },
        { q: '「He has been to America.」の 意味は？', opts: ['彼は今アメリカにいる','彼はアメリカに行ったことがある','彼はアメリカに行く','彼はアメリカが好き'], correct: 1, hint: 'has been to=〜に行ったことがある！', explain: '現在完了形（経験）。has been to=〜へ行ったことがある' },
        { q: '「The book was written by her.」は 何文？', opts: ['能動文','受動文（受け身）','疑問文','命令文'], correct: 1, hint: 'was written=書かれた（受け身）', explain: '受動態（受け身）。be動詞+過去分詞で「〜される・された」' },
        { q: '「How long」は 何を 聞く？', opts: ['どのくらいの長さ・時間','いくつ','どのように','どれほど重い'], correct: 0, hint: 'long=長さ・時間！', explain: 'How long=どのくらいの長さ/時間。「How long does it take?」' },
        { q: '「I think that she is kind.」で that 以下は？', opts: ['主語','目的語（that節）','補語','動詞'], correct: 1, hint: 'I think の 内容を 伝える！', explain: 'that節=「〜ということ」を表す名詞節で目的語になる' },
        { q: '「Can you help me?」への 正しい 返答は？', opts: ['Yes, I do.','Sure! / Of course!','Yes, I am.','No, I don\'t.'], correct: 1, hint: '「もちろん！」は 英語で？', explain: 'Sure! / Of course!（もちろん！）が自然な返答' },
        { q: '「Let\'s play basketball!」の 意味は？', opts: ['バスケをしたい','バスケをしよう！','バスケをする','バスケが好き'], correct: 1, hint: 'Let\'s=〜しよう！', explain: 'Let\'s=〜しましょう・しよう（勧誘）' },
        { q: '英語の アルファベットは 何文字？', opts: ['24文字','25文字','26文字','27文字'], correct: 2, hint: 'A〜Zまで 数えよう！', explain: 'A〜Z、a〜zの26文字。大文字・小文字がある' },
      ],
    }
  },
};
