// quiz-data.js - クイズデータ（小2〜小6対応・学年1位レベル）
const QUIZ_DATA = {
  math: {
    name: 'さんすうの どうくつ',
    color: '#FF6600',
    portalColor: 0xFF6600,
    grades: {
      grade2: [
        { q: '32 + 15 = ?', opts: ['47','45','57','43'], correct: 0, hint: 'じゅうのくらいと いちのくらいに わけよう！', explain: '32+15=47' },
        { q: '21 + 36 = ?', opts: ['57','55','67','53'], correct: 0, hint: 'くらいごとに たそう！', explain: '21+36=57' },
        { q: '48 + 23 = ?', opts: ['61','71','68','65'], correct: 1, hint: 'くりあがりに ちゅうい！', explain: '48+23=71（8+3=11 くりあがり）' },
        { q: '75 - 32 = ?', opts: ['43','33','47','41'], correct: 0, hint: 'くらいごとに ひこう！', explain: '75-32=43' },
        { q: '53 - 28 = ?', opts: ['25','35','23','27'], correct: 0, hint: 'くりさがりに ちゅうい！', explain: '53-28=25' },
        { q: '2 × 3 = ?', opts: ['5','6','8','4'], correct: 1, hint: 'に さん は？', explain: '2×3=6（に さん が ろく）' },
        { q: '3 × 4 = ?', opts: ['7','10','12','9'], correct: 2, hint: 'さん し は？', explain: '3×4=12（さん し じゅうに）' },
        { q: '5 × 6 = ?', opts: ['25','30','35','28'], correct: 1, hint: 'ご ろく は？', explain: '5×6=30（ご ろく さんじゅう）' },
        { q: '4 × 7 = ?', opts: ['24','28','32','21'], correct: 1, hint: 'し しち は？', explain: '4×7=28（し しち にじゅうはち）' },
        { q: '8 × 9 = ?', opts: ['63','72','81','64'], correct: 1, hint: 'はち く は？', explain: '8×9=72（はち く しちじゅうに）' },
        { q: '1時間 = なん分？', opts: ['30分','50分','60分','100分'], correct: 2, hint: '時計が 1まわりで！', explain: '1時間=60分' },
        { q: '1cm = なんmm？', opts: ['5mm','10mm','20mm','100mm'], correct: 1, hint: '10のメモリで 1cm！', explain: '1cm=10mm' },
        { q: '三角形の へんの かずは？', opts: ['2ほん','3ほん','4ほん','5ほん'], correct: 1, hint: '「三」が ついてるよ！', explain: '三角形は へんが 3ほん' },
        { q: '100円玉が 3まい で いくら？', opts: ['200円','300円','400円','30円'], correct: 1, hint: '100+100+100=?', explain: '100×3=300円' },
        { q: '正方形の へんの かずは？', opts: ['3ほん','4ほん','5ほん','6ほん'], correct: 1, hint: '4つの かどが あるよ！', explain: '正方形は へんが 4ほん、ぜんぶ 同じ 長さ' },
        { type:'truefalse', q:'5 × 8 = 40　ただしい？', opts:['○','×'], correct:0, hint:'ご は ？', explain:'5×8=40（ご は しじゅう）せいかい！' },
        { type:'truefalse', q:'70 + 40 = 100　ただしい？', opts:['○','×'], correct:1, hint:'70と40を たしてみよう', explain:'70+40=110 です' },
        { type:'truefalse', q:'三角形の かどの 数は 3つ　ただしい？', opts:['○','×'], correct:0, hint:'三角形の「三」！', explain:'三角形は かどが 3つ せいかい！' },
        { type:'keypad', q:'8 × 7 = ?', answer:'56', explain:'8×7=56（はち しち ごじゅうろく）' },
        { type:'keypad', q:'36 + 47 = ?', answer:'83', explain:'36+47=83（くりあがりあり）' },
        { type:'keypad', q:'100 - 38 = ?', answer:'62', explain:'100-38=62' },
        { type:'keypad', q:'9 × 6 = ?', answer:'54', explain:'9×6=54（く ろく ごじゅうし）' },
        { q: '67 + 18 = ?', opts: ['75','85','84','86'], correct: 1, hint: 'くりあがりに ちゅうい！', explain: '67+18=85' },
        { q: '93 - 47 = ?', opts: ['44','46','56','54'], correct: 1, hint: 'くりさがりに ちゅうい！', explain: '93-47=46' },
        { q: '1L は なんdL？', opts: ['2dL','5dL','10dL','100dL'], correct: 2, hint: 'dL（デシリットル）は L の 1/10！', explain: '1L=10dL' },
        { q: '7 × 9 = ?', opts: ['56','63','72','54'], correct: 1, hint: 'しち く は？', explain: '7×9=63（しち く ろくじゅうさん）' },
        { q: '長方形の かどの 数は？', opts: ['2つ','3つ','4つ','5つ'], correct: 2, hint: '4つの かどが あるよ！', explain: '長方形は 4つの かどが ある' },
        { q: '4 × 8 = ?', opts: ['28','32','36','40'], correct: 1, hint: 'し は は？', explain: '4×8=32（し は さんじゅうに）' },
        { q: '62 + 39 = ?', opts: ['91','101','99','100'], correct: 1, hint: 'くりあがりに ちゅうい！', explain: '62+39=101' },
        { q: '「午前10時」から「正午（12時）」まで 何時間？', opts: ['1時間','2時間','3時間','4時間'], correct: 1, hint: '10時→11時→12時', explain: '午前10時から正午まで2時間' },
        { type:'truefalse', q:'1m = 100cm　ただしい？', opts:['○','×'], correct:0, hint:'1メートルは 何センチ？', explain:'1m=100cm せいかい！' },
        { type:'truefalse', q:'4 × 6 = 26　ただしい？', opts:['○','×'], correct:1, hint:'し ろく は？', explain:'4×6=24 です' },
        { type:'truefalse', q:'一週間は 7日　ただしい？', opts:['○','×'], correct:0, hint:'月曜〜日曜！', explain:'一週間=7日 せいかい！' },
        { type:'truefalse', q:'時計の ながい はりが いっしゅう すると 60分　ただしい？', opts:['○','×'], correct:0, hint:'1時間=60分！', explain:'ながい はりが いっしゅう すると 60分 = 1時間 せいかい！' },
        { type:'keypad', q:'7 × 6 = ?', answer:'42', explain:'7×6=42（しち ろく しじゅうに）' },
        { type:'keypad', q:'53 + 29 = ?', answer:'82', explain:'53+29=82' },
        { type:'keypad', q:'80 - 34 = ?', answer:'46', explain:'80-34=46' },
      ],
      grade3: [
        { q: '125 + 68 = ?', opts: ['183','193','203','173'], correct: 1, hint: 'くりあがりに ちゅうい！', explain: '125+68=193' },
        { q: '500 - 237 = ?', opts: ['273','263','363','253'], correct: 1, hint: 'ゼロから ひくよ！', explain: '500-237=263' },
        { q: '12 ÷ 4 = ?', opts: ['2','3','4','5'], correct: 1, hint: '4のだんで 考えよう！', explain: '12÷4=3（4×3=12）' },
        { q: '24 ÷ 6 = ?', opts: ['3','4','5','6'], correct: 1, hint: '6のだんで 確認！', explain: '24÷6=4（6×4=24）' },
        { q: '7 × 8 = ?', opts: ['54','56','58','48'], correct: 1, hint: 'しち は ？', explain: '7×8=56（しち は ごじゅうろく）' },
        { q: '6 × 9 = ?', opts: ['45','54','56','63'], correct: 1, hint: 'ろく く ？', explain: '6×9=54（ろく く ごじゅうし）' },
        { q: '0.3 + 0.5 = ?', opts: ['0.7','0.8','1.0','0.9'], correct: 1, hint: '小数点を そろえよう！', explain: '0.3+0.5=0.8' },
        { q: '1m = なんcm？', opts: ['10cm','100cm','1000cm','50cm'], correct: 1, hint: 'メートルより 小さい 単位！', explain: '1m=100cm' },
        { q: '1L = なんmL？', opts: ['10mL','100mL','500mL','1000mL'], correct: 3, hint: 'ポーション なんこぶん？', explain: '1L=1000mL' },
        { q: '縦4cm 横6cmの 長方形の 面積は？', opts: ['10cm²','20cm²','24cm²','40cm²'], correct: 2, hint: 'たて × よこ！', explain: '面積=4×6=24cm²' },
        { q: '56 ÷ 7 = ?', opts: ['6','7','8','9'], correct: 2, hint: '7のだんで 考えよう！', explain: '56÷7=8（7×8=56）' },
        { q: '1kg = なんg？', opts: ['10g','100g','1000g','10000g'], correct: 2, hint: 'kは1000のことだよ！', explain: '1kg=1000g' },
        { type:'truefalse', q:'1km = 1000m　ただしい？', opts:['○','×'], correct:0, hint:'k（キロ）は1000のこと！', explain:'1km=1000m せいかい！' },
        { type:'truefalse', q:'三角形の 内角の和は 360度　ただしい？', opts:['○','×'], correct:1, hint:'三角形と 四角形は ちがうよ', explain:'三角形の内角の和は180度です' },
        { type:'keypad', q:'63 ÷ 9 = ?', answer:'7', explain:'63÷9=7（9×7=63）' },
        { type:'keypad', q:'48 ÷ 6 = ?', answer:'8', explain:'48÷6=8（6×8=48）' },
        { type:'keypad', q:'27 × 4 = ?', answer:'108', explain:'27×4=108' },
        { q: '372 + 185 = ?', opts: ['547','557','457','537'], correct: 1, hint: 'くらいごとに たそう！', explain: '372+185=557' },
        { q: '600 - 348 = ?', opts: ['248','252','262','242'], correct: 1, hint: 'ゼロから ひくよ！', explain: '600-348=252' },
        { q: '35 ÷ 5 = ?', opts: ['5','6','7','8'], correct: 2, hint: '5のだんで 考えよう！', explain: '35÷5=7（5×7=35）' },
        { q: '72 ÷ 8 = ?', opts: ['8','9','7','6'], correct: 1, hint: '8のだんで 確認！', explain: '72÷8=9（8×9=72）' },
        { q: '0.7 + 0.6 = ?', opts: ['1.2','1.3','0.13','1.4'], correct: 1, hint: '7+6=13、小数点を そろえよう', explain: '0.7+0.6=1.3' },
        { q: '三角形の 内角の和は？', opts: ['90度','180度','270度','360度'], correct: 1, hint: 'さんかくけい！', explain: '三角形の内角の和=180度' },
        { q: '直径10cmの 円の 半径は？', opts: ['5cm','10cm','20cm','2cm'], correct: 0, hint: '半径=直径÷2！', explain: '半径=10÷2=5cm' },
        { q: '17 ÷ 5 の 答えを あまりも 書くと？', opts: ['3あまり2','3あまり1','4あまり3','2あまり7'], correct: 0, hint: '5×3=15、17-15=？', explain: '17÷5=3あまり2（5×3=15、17-15=2）' },
        { type:'truefalse', q:'5×7=35　ただしい？', opts:['○','×'], correct:0, hint:'ご しち は？', explain:'5×7=35 せいかい！' },
        { type:'truefalse', q:'1L = 100mL　ただしい？', opts:['○','×'], correct:1, hint:'Lと mLの 関係！', explain:'1L=1000mL です' },
        { type:'truefalse', q:'正方形は 長方形の 一種　ただしい？', opts:['○','×'], correct:0, hint:'長方形の 条件は？', explain:'正方形はすべての辺が等しい長方形なので、長方形の一種 せいかい！' },
        { type:'keypad', q:'54 ÷ 6 = ?', answer:'9', explain:'54÷6=9（6×9=54）' },
        { type:'keypad', q:'1L = なんmL？', answer:'1000', explain:'1L=1000mL' },
      ],
      grade4: [
        { q: '1/2 + 1/4 = ?', opts: ['2/6','3/4','1/4','2/4'], correct: 1, hint: '分母を 合わせよう！', explain: '1/2=2/4、2/4+1/4=3/4' },
        { q: '3/4 - 1/8 = ?', opts: ['2/4','5/8','4/8','2/8'], correct: 1, hint: '3/4を 8分の？に 直そう！', explain: '3/4=6/8、6/8-1/8=5/8' },
        { q: '3/6 を 約分すると？', opts: ['1/2','1/3','2/3','3/3'], correct: 0, hint: '分子と 分母を 3で わろう！', explain: '3÷3=1、6÷3=2 → 1/2' },
        { q: '2.5 × 4 = ?', opts: ['8','9','10','11'], correct: 2, hint: '2.5=2+0.5に 分けよう！', explain: '2×4+0.5×4=8+2=10' },
        { q: '縦5cm 横8cmの 長方形の 面積は？', opts: ['13cm²','26cm²','40cm²','56cm²'], correct: 2, hint: 'たて × よこ！', explain: '面積=5×8=40cm²' },
        { q: '底辺8cm 高さ5cmの 三角形の 面積は？', opts: ['13cm²','20cm²','40cm²','80cm²'], correct: 1, hint: '底辺 × 高さ ÷ 2！', explain: '8×5÷2=20cm²' },
        { q: '直角は 何度？', opts: ['45度','90度','180度','360度'], correct: 1, hint: 'L字型の かど！', explain: '直角=90度' },
        { q: '三角形の 内角の和は？', opts: ['90度','180度','270度','360度'], correct: 1, hint: '3つのかどを 全部たすと？', explain: '三角形の内角の和=180度' },
        { q: '1億は 何万？', opts: ['100万','1000万','10000万','100000万'], correct: 2, hint: '0の 数を 数えよう！', explain: '1億=10000万' },
        { q: '4850を 百の位で 四捨五入すると？', opts: ['4000','4800','5000','4900'], correct: 2, hint: '百の位の数(8)は 5以上？', explain: '百の位が8（≧5）なので切り上げ → 5000' },
        { q: '84の 約数でないものは？', opts: ['4','6','7','5'], correct: 3, hint: '84÷5は 割り切れる？', explain: '84÷5=16余り4なので5は約数でない' },
        { q: '角柱の 底面は 何個？', opts: ['1個','2個','3個','4個'], correct: 1, hint: '上と 下に あるよ！', explain: '角柱は底面が2個（上面・下面）' },
        { type:'truefalse', q:'直角は 90度　ただしい？', opts:['○','×'], correct:0, hint:'L字型の かど！', explain:'直角=90度 せいかい！' },
        { type:'truefalse', q:'四角形の 内角の和は 270度　ただしい？', opts:['○','×'], correct:1, hint:'三角形×2で 考えよう', explain:'四角形の内角の和は360度です' },
        { type:'keypad', q:'縦6cm 横9cmの 長方形の 面積は？ (cm²)', answer:'54', explain:'6×9=54cm²（たて×よこ）' },
        { type:'keypad', q:'底辺10cm 高さ6cmの 三角形の 面積は？ (cm²)', answer:'30', explain:'10×6÷2=30cm²' },
        { q: '2/3 + 1/3 = ?', opts: ['1','2/6','3/3','2/3'], correct: 0, hint: '分母が 同じなら 分子を たす！', explain: '2/3+1/3=3/3=1' },
        { q: '5/6 - 1/6 = ?', opts: ['4/12','4/6','5/36','0'], correct: 1, hint: '分母が 同じなら 分子を ひく！', explain: '5/6-1/6=4/6=2/3' },
        { q: '平行四辺形の 面積は？（底辺8cm 高さ5cm）', opts: ['13cm²','26cm²','40cm²','80cm²'], correct: 2, hint: '底辺×高さ！', explain: '平行四辺形の面積=底辺×高さ=8×5=40cm²' },
        { q: '3748を 百の位で 四捨五入すると？', opts: ['3700','3750','3800','4000'], correct: 0, hint: '十の位(4)を 見よう！', explain: '3748の十の位は4（<5）なので切り捨て → 3700' },
        { q: '84の 約数は いくつ？', opts: ['10個','12個','8個','6個'], correct: 1, hint: '1,2,3,4,6,7,12,14,21,28,42,84…', explain: '84の約数は 1,2,3,4,6,7,12,14,21,28,42,84 の12個' },
        { type:'truefalse', q:'2/4 と 1/2 は 同じ 大きさ　ただしい？', opts:['○','×'], correct:0, hint:'2/4を 約分すると？', explain:'2/4=1/2（2と4を2で割る） せいかい！' },
        { type:'truefalse', q:'角柱の 側面は 長方形である　ただしい？', opts:['○','×'], correct:0, hint:'角柱の 側面の 形は？', explain:'角柱の側面は長方形 せいかい！' },
        { type:'keypad', q:'縦6cm 横9cmの 長方形の 面積は？ (cm²)', answer:'54', explain:'6×9=54cm²（たて×よこ）' },
        { type:'keypad', q:'縦8cm 横7cmの 平行四辺形の 面積は？ (cm²)', answer:'56', explain:'底辺×高さ=8×7=56cm²' },
      ],
      grade5: [
        { q: '2/3 × 3/4 = ?', opts: ['5/7','1/2','6/12','2/4'], correct: 1, hint: '分子どうし、分母どうし かけよう！', explain: '2×3=6、3×4=12 → 6/12=1/2' },
        { q: '3/4 ÷ 3/8 = ?', opts: ['9/32','1','2','3/2'], correct: 2, hint: '÷は 逆数を かける！', explain: '3/4 × 8/3 = 24/12 = 2' },
        { q: '0.6 × 1.5 = ?', opts: ['0.7','0.9','1.0','1.8'], correct: 1, hint: '6×15=90、小数点を 2つ 左へ！', explain: '0.6×1.5=0.90=0.9' },
        { q: '半径5cmの 円の 面積は？（π=3.14）', opts: ['15.7cm²','31.4cm²','78.5cm²','157cm²'], correct: 2, hint: '面積=半径×半径×π！', explain: '5×5×3.14=78.5cm²' },
        { q: '縦3cm 横4cm 高さ5cmの 直方体の 体積は？', opts: ['12cm³','60cm³','120cm³','24cm³'], correct: 1, hint: 'たて×よこ×たかさ！', explain: '3×4×5=60cm³' },
        { q: '4つの数 10,8,6,4の 平均は？', opts: ['6','7','8','9'], correct: 1, hint: '全部たして 個数で わる！', explain: '(10+8+6+4)÷4=28÷4=7' },
        { q: '時速60kmで 2時間 走ると 何km？', opts: ['30km','60km','120km','180km'], correct: 2, hint: '速さ×時間=距離！', explain: '60×2=120km' },
        { q: '30の 20% は？', opts: ['6','10','12','15'], correct: 0, hint: '30×0.2=?', explain: '30×20÷100=30×0.2=6' },
        { q: '公倍数：4と6の 最小公倍数は？', opts: ['10','12','18','24'], correct: 1, hint: '4の倍数と 6の倍数を 書いてみよう！', explain: '4の倍数:4,8,12… 6の倍数:6,12… 最小=12' },
        { q: '公約数：12と18の 最大公約数は？', opts: ['3','4','6','9'], correct: 2, hint: '12と18を 同じ数で われる 最大は？', explain: '12=2²×3、18=2×3² → GCD=2×3=6' },
        { q: '四角形の 内角の和は？', opts: ['180度','270度','360度','450度'], correct: 2, hint: '三角形を 2つに 分けると？', explain: '四角形=三角形×2 → 180×2=360度' },
        { q: '1.2 ÷ 0.4 = ?', opts: ['0.3','3','0.48','2.4'], correct: 1, hint: '両方を 10倍すると？', explain: '1.2÷0.4=12÷4=3' },
        { type:'truefalse', q:'四角形の 内角の和は 360度　ただしい？', opts:['○','×'], correct:0, hint:'三角形×2！', explain:'四角形=三角形2つ分 → 180×2=360度 せいかい！' },
        { type:'truefalse', q:'時速60kmで 3時間 走ると 150km　ただしい？', opts:['○','×'], correct:1, hint:'速さ×時間=距離', explain:'60×3=180km です' },
        { type:'keypad', q:'時速50kmで 3時間 走ると 何km？', answer:'150', explain:'50×3=150km（速さ×時間）' },
        { type:'keypad', q:'半径4cmの 円の 面積は？\n（π=3.14、答えは整数部分のみ）', answer:'50', explain:'4×4×3.14=50.24 ≒ 50cm²' },
        { q: '1/3 × 6 = ?', opts: ['2','6/3','6/18','1/2'], correct: 0, hint: '分子に かける！', explain: '1/3×6=6/3=2' },
        { q: '4/5 ÷ 2 = ?', opts: ['8/5','2/5','4/10','2/10'], correct: 1, hint: '÷2は 分母に ×2！', explain: '4/5÷2=4/10=2/5' },
        { q: '縦4cm 横5cm 高さ6cmの 直方体の 体積は？', opts: ['15cm³','60cm³','120cm³','90cm³'], correct: 2, hint: 'たて×よこ×たかさ！', explain: '4×5×6=120cm³' },
        { q: '全体のうち 40%が 60人。 全体は 何人？', opts: ['24人','100人','150人','240人'], correct: 2, hint: '全体×0.4=60 → 全体=？', explain: '60÷0.4=150人' },
        { q: '5と6の 最小公倍数は？', opts: ['11','24','30','60'], correct: 2, hint: '5の倍数: 5,10,15,20,25,30… 6の倍数: 6,12,18,24,30…', explain: '最小公倍数=30' },
        { q: '時速36kmは 秒速 何m？', opts: ['1m','10m','36m','100m'], correct: 1, hint: '36km/h = 36000m/3600s', explain: '36000÷3600=10m/秒' },
        { type:'truefalse', q:'時速80kmで 2.5時間 走ると 200km　ただしい？', opts:['○','×'], correct:0, hint:'80×2.5=?', explain:'80×2.5=200km せいかい！' },
        { type:'truefalse', q:'2/3 > 3/4　ただしい？', opts:['○','×'], correct:1, hint:'通分して 比べよう！', explain:'2/3=8/12、3/4=9/12 → 2/3<3/4 なので × です' },
        { type:'keypad', q:'縦5cm 横6cm 高さ4cmの 直方体の 体積は？ (cm³)', answer:'120', explain:'5×6×4=120cm³' },
      ],
      grade6: [
        { q: '2 : 3 = 4 : ?', opts: ['5','6','8','9'], correct: 1, hint: '比の 内項の積=外項の積！', explain: '2×?=3×4=12 → ?=6' },
        { q: 'xがyに 正比例するとき x=2でy=6。x=5のとき y=?', opts: ['10','12','15','18'], correct: 2, hint: 'y=kx の kを 求めよう！', explain: 'k=6÷2=3 → y=3×5=15' },
        { q: '底面積10cm² 高さ6cmの 角柱の 体積は？', opts: ['16cm³','60cm³','160cm³','600cm³'], correct: 1, hint: '体積=底面積×高さ！', explain: '10×6=60cm³' },
        { q: '速さ120km/h 距離360kmを 走る 時間は？', opts: ['2時間','3時間','4時間','5時間'], correct: 1, hint: '時間=距離÷速さ！', explain: '360÷120=3時間' },
        { q: '全体のうち 75%が 90人。 全体は 何人？', opts: ['67人','100人','120人','135人'], correct: 2, hint: '全体×0.75=90 → 全体=?', explain: '90÷0.75=120人' },
        { q: 'n角形の 内角の和の 公式は？', opts: ['90(n-1)°','180(n-2)°','180(n-1)°','360°'], correct: 1, hint: '三角形=180°、四角形=360°…', explain: 'n角形の内角の和=180°×(n-2)' },
        { q: '1000mL = 何dL？', opts: ['1dL','10dL','100dL','1000dL'], correct: 1, hint: '1dL=100mL！', explain: '1000mL÷100=10dL' },
        { q: '仕事全体を1とする。Aが1/3日でできる。3日でいくつ？', opts: ['1','3','1/3','1/9'], correct: 0, hint: '1日に1/3できるなら 3日では？', explain: '1/3×3=1（全体完成）' },
        { q: '縮尺1/25000の 地図で 4cmは 実際 何km？', opts: ['0.1km','1km','4km','100km'], correct: 1, hint: '4cm×25000=?cm を kmに！', explain: '4×25000=100000cm=1000m=1km' },
        { q: '次のうち 素数は どれ？', opts: ['1','4','9','11'], correct: 3, hint: '1と自分だけで わり切れる数！', explain: '1は素数でない。11=11×1のみ → 素数' },
        { q: 'π=3.14 として 直径10cmの 円周は？', opts: ['15.7cm','31.4cm','78.5cm','100cm'], correct: 1, hint: '円周=直径×π！', explain: '10×3.14=31.4cm' },
        { q: '42を 素因数分解すると？', opts: ['2×21','2×3×7','3×14','6×7'], correct: 1, hint: '小さい 素数から わっていこう！', explain: '42÷2=21、21÷3=7 → 2×3×7' },
        { q: '3 : 5 = 12 : ?', opts: ['4','15','20','25'], correct: 2, hint: '3×?=5×12', explain: '3×?=60 → ?=20' },
        { q: 'xとyが 反比例。x=3でy=8。x=6のとき y=?', opts: ['4','8','16','24'], correct: 0, hint: 'x×y = 一定！', explain: '3×8=24（一定）→ 6×y=24 → y=4' },
        { q: '底面が半径3cmの 円の 面積は？（π=3.14）', opts: ['9.42cm²','18.84cm²','28.26cm²','56.52cm²'], correct: 2, hint: '半径×半径×π！', explain: '3×3×3.14=28.26cm²' },
        { q: '円の 面積の 公式は？', opts: ['直径×π','半径×π×2','半径×半径×π','直径×直径×π'], correct: 2, hint: '半径²×π！', explain: '円の面積=半径²×π（パイ）' },
        { type:'truefalse', q:'x=2 y=6 のとき y÷x=3。 これは 正比例　ただしい？', opts:['○','×'], correct:0, hint:'y=kx の kが 一定なら正比例！', explain:'y÷x=3（一定）なので y=3x の正比例 せいかい！' },
        { type:'truefalse', q:'縮尺 1/50000の 地図で 2cmは 実際 1km　ただしい？', opts:['○','×'], correct:0, hint:'2×50000=?cm', explain:'2×50000=100000cm=1000m=1km せいかい！' },
        { type:'keypad', q:'全体の 60%が 90人のとき 全体は 何人？', answer:'150', explain:'90÷0.6=150人' },
        { type:'keypad', q:'4 : 7 = 20 : ?', answer:'35', explain:'4×?=7×20=140 → ?=35' },
      ],
    }
  },
  japanese: {
    name: 'こくごの もり',
    color: '#00CC44',
    portalColor: 0x00CC44,
    grades: {
      grade2: [
        { q: '「花」の よみかたは？', opts: ['き','はな','くさ','は'], correct: 1, hint: 'きれいに さくよ！', explain: '「花」→ はな' },
        { q: '「空」の よみかたは？', opts: ['うみ','そら','やま','かわ'], correct: 1, hint: '雲が うかんでる！', explain: '「空」→ そら' },
        { q: '「石」の よみかたは？', opts: ['つち','いし','かわ','ほし'], correct: 1, hint: 'マイクラで ほれるよ！', explain: '「石」→ いし' },
        { q: '「大きい」の はんたいは？', opts: ['ひくい','ちいさい','ながい','みじかい'], correct: 1, hint: 'クリーパーは大きい、こうもりは？', explain: '「大きい」の はんたいは「小さい」' },
        { q: '「走る・歩く・およぐ」の なかまは？', opts: ['りんご','とぶ','赤い','きれい'], correct: 1, hint: 'からだを うごかす ことば！', explain: '走る・歩く・およぐ・とぶ は どれも うごきを あらわす ことば' },
        { q: '「とても」と 同じような 意味の ことばは？', opts: ['すこし','たいへん','あまり','ちょっと'], correct: 1, hint: 'おなじ 意味の ことば！', explain: '「とても」≒「たいへん」' },
        { q: '「犬」と「猫」、五十音で 先に くるのは？', opts: ['犬（い）','猫（ね）','同じ','わからない'], correct: 0, hint: '「い」と「ね」どちらが先？', explain: '五十音では「い」が「ね」より 前に くる' },
        { q: '「山」の よみかたは？', opts: ['かわ','うみ','やま','たに'], correct: 2, hint: 'マイクラで のぼれるよ！', explain: '「山」→ やま' },
        { q: '「明るい」の はんたいは？', opts: ['せまい','くらい','ひくい','よわい'], correct: 1, hint: 'ナイトモードは？', explain: '「明るい」の はんたいは「暗い（くらい）」' },
        { type:'truefalse', q:'「火曜日」の よみかたは「かようび」　ただしい？', opts:['○','×'], correct:0, hint:'曜日の よみかた！', explain:'「火曜日」→ かようび せいかい！' },
        { type:'truefalse', q:'「雨」の よみかたは「かみなり」　ただしい？', opts:['○','×'], correct:1, hint:'空から ふってくる もの！', explain:'「雨」→ あめ です' },
        { type:'truefalse', q:'「大きい」と「小さい」は はんたいの ことば　ただしい？', opts:['○','×'], correct:0, hint:'はんたいの 意味の ことば！', explain:'「大きい」↔「小さい」は はんたいの ことば せいかい！' },
        { q: '「木」の よみかたは？', opts: ['き','くさ','はな','みず'], correct: 0, hint: 'マイクラで 切れるよ！', explain: '「木」→ き' },
        { q: '「水」の よみかたは？', opts: ['ほのお','みず','つち','かぜ'], correct: 1, hint: 'のどが かわいたら！', explain: '「水」→ みず' },
        { q: '「休む」の よみかたは？', opts: ['やすむ','あそぶ','ねむる','はたらく'], correct: 0, hint: 'つかれたら ○○む！', explain: '「休む」→ やすむ' },
        { q: '「上」と「下」は どんな 関係？', opts: ['同じ 意味','はんたいの 意味','にた 意味','かんけいなし'], correct: 1, hint: 'かみと しも！', explain: '「上」と「下」は はんたいの ことば' },
        { q: '「長い」の はんたいは？', opts: ['ひろい','みじかい','ふとい','おおきい'], correct: 1, hint: '糸や ロープの ながさ！', explain: '「長い」の はんたいは「短い（みじかい）」' },
        { q: '「強い」の はんたいは？', opts: ['かたい','よわい','はやい','おそい'], correct: 1, hint: 'ちからが ない！', explain: '「強い」の はんたいは「弱い（よわい）」' },
        { q: '「森・川・山・海」の なかまわけは？', opts: ['たべもの','しぜん','どうぶつ','いろ'], correct: 1, hint: 'しぜんに あるものだよ！', explain: '森・川・山・海は ぜんぶ しぜんのもの' },
        { q: '正しい 文は どれ？', opts: ['ほんを ねる','ごはんを うたう','えを かく','うたを たべる'], correct: 2, hint: '絵は かくもの！', explain: '「絵を かく」が 正しい くみあわせ' },
        { type:'truefalse', q:'「右」と「左」は はんたいの 意味　ただしい？', opts:['○','×'], correct:0, hint:'みぎと ひだり！', explain:'「右」と「左」は はんたいの ことば せいかい！' },
        { type:'truefalse', q:'「雨」の よみかたは「かわ」　ただしい？', opts:['○','×'], correct:1, hint:'空から ふってくる もの！', explain:'「雨」→ あめ です' },
        { type:'truefalse', q:'「走る」は うごきを あらわす ことば　ただしい？', opts:['○','×'], correct:0, hint:'からだを うごかす！', explain:'「走る」は からだを うごかす ことば せいかい！' },
        { type:'truefalse', q:'「木・草・花」は どれも しぜんの なかま　ただしい？', opts:['○','×'], correct:0, hint:'しぜんの ものは？', explain:'木・草・花は どれも しぜんのもの せいかい！' },
        { type:'truefalse', q:'一日は 24時間　ただしい？', opts:['○','×'], correct:0, hint:'朝から また 朝まで！', explain:'一日=24時間 せいかい！' },
      ],
      grade3: [
        { q: '「春」の よみかたは？', opts: ['なつ','はる','あき','ふゆ'], correct: 1, hint: 'さくらが さく きせつ！', explain: '「春」→ はる。春夏秋冬の最初。' },
        { q: '「海」の よみかたは？', opts: ['やま','かわ','うみ','もり'], correct: 2, hint: 'さかなが いる ひろいところ！', explain: '「海」→ うみ' },
        { q: '「森」は なにが たくさん？', opts: ['みず','き','いし','はな'], correct: 1, hint: '「木」が 3つ あるよ！', explain: '「森」という字は木が3つ。木がたくさんある場所。' },
        { q: '「走る」は なに？', opts: ['名詞','動詞','形容詞','接続詞'], correct: 1, hint: 'からだを うごかす ことば！', explain: '「走る」は動作を表す動詞' },
        { q: '「美しい」は なに？', opts: ['名詞','動詞','形容詞','接続詞'], correct: 2, hint: 'ようすを あらわすよ！', explain: '「美しい」はようす（状態）を表す形容詞' },
        { q: '「ねこの手も かりたい」の いみは？', opts: ['ねこが すき','とても いそがしい','ねこの あし','てが ちいさい'], correct: 1, hint: '「ねこの ても かりたい！」', explain: '「猫の手も借りたい」=とても忙しいことわざ' },
        { q: '「光」の よみかたは？', opts: ['かぜ','ひかり','おと','いろ'], correct: 1, hint: 'グロウストーンの ○○○！', explain: '「光」→ ひかり' },
        { q: '「友」の よみかたは？', opts: ['あに','いもうと','とも','おや'], correct: 2, hint: 'いっしょに あそぶ ひと！', explain: '「友」→ とも。友達。' },
        { q: '「星」の よみかたは？', opts: ['ほし','つき','そら','くも'], correct: 0, hint: 'よるに キラキラ ひかるよ！', explain: '「星」→ ほし' },
        { q: '「急いで」の 使い方で 正しいのは？', opts: ['急いで かんがえる','急いで ねる','急いで かける','急いで まつ'], correct: 2, hint: '「急いで」は 速く動くとき！', explain: '急いでかける＝急いで走る。急いで待つ・寝るは矛盾する' },
        { type:'truefalse', q:'「走る」は 動詞である　ただしい？', opts:['○','×'], correct:0, hint:'からだを 動かす ことば！', explain:'「走る」は動作を表す動詞 せいかい！' },
        { type:'truefalse', q:'「美しい」は 名詞である　ただしい？', opts:['○','×'], correct:1, hint:'ようすを あらわす ことば？', explain:'「美しい」はようすを表す形容詞です' },
        { type:'truefalse', q:'「猫の手も借りたい」は とても いそがしい という 意味　ただしい？', opts:['○','×'], correct:0, hint:'ことわざ！', explain:'「猫の手も借りたい」=とても忙しい せいかい！' },
        { q: '「水泳」の 読み方は？', opts: ['みずえい','すいえい','みずおよぎ','すいよう'], correct: 1, hint: 'スイミング！', explain: '「水泳」→ すいえい' },
        { q: '「電気」の 読み方は？', opts: ['でんき','かみなり','でんち','かがく'], correct: 0, hint: 'ライトに 必要なもの！', explain: '「電気」→ でんき' },
        { q: '「ことわざ」とは？', opts: ['外来語','昔から伝わる教え','動物の名前','地名'], correct: 1, hint: '「七転び八起き」など！', explain: 'ことわざ=昔から伝わる短い教え・知恵' },
        { q: '「石橋を たたいて 渡る」の 意味は？', opts: ['石を 集める','橋を なおす','用心深く 行動する','急いで 渡る'], correct: 2, hint: 'よく 確かめてから！', explain: '「石橋をたたいて渡る」=十分に確かめてから慎重に行動すること' },
        { q: '「主語+述語」の 文は？', opts: ['きれいな花','花が咲く','花の色','花だけ'], correct: 1, hint: '「○○が ～する」！', explain: '「花が咲く」= 主語(花が)+述語(咲く)' },
        { q: '「植物」に 当てはまらないのは？', opts: ['バラ','タンポポ','コイ','ひまわり'], correct: 2, hint: 'さかなは しょくぶつ？', explain: 'コイは魚（動物）。バラ・タンポポ・ひまわりは植物' },
        { q: '「音読み」と「訓読み」の 違いは？', opts: ['音読みは日本語の読み方','音読みは中国語由来の読み方','訓読みは外来語','どちらも同じ'], correct: 1, hint: '「山」→ サン(音)・やま(訓)！', explain: '音読みは中国語由来の読み方。訓読みは日本語の読み方' },
        { type:'truefalse', q:'「七転び八起き」は 何度 失敗しても あきらめない という 意味　ただしい？', opts:['○','×'], correct:0, hint:'七回 転んで 八回 起きる！', explain:'「七転び八起き」=何度失敗しても諦めない せいかい！' },
        { type:'truefalse', q:'「接続詞」は 文と 文を つなぐ ことばである　ただしい？', opts:['○','×'], correct:0, hint:'「そして」「しかし」など！', explain:'接続詞は文をつなぐ言葉 せいかい！' },
        { type:'truefalse', q:'「冬」の 漢字の 読み方は「ふゆ」　ただしい？', opts:['○','×'], correct:0, hint:'四季の 一つ！', explain:'「冬」→ ふゆ せいかい！' },
        { type:'truefalse', q:'「走る」は 形容詞である　ただしい？', opts:['○','×'], correct:1, hint:'動作？ ようす？', explain:'「走る」は動作を表す動詞です（形容詞ではない）' },
        { type:'truefalse', q:'「雲一つない 青空」の「雲一つない」は 修飾語　ただしい？', opts:['○','×'], correct:0, hint:'「青空」を 説明してる？', explain:'「雲一つない」が「青空」を修飾する修飾語 せいかい！' },
      ],
      grade4: [
        { q: '「季節」の読み方は？', opts: ['きせつ','きぶん','けしき','かんせつ'], correct: 0, hint: '春・夏・秋・冬のこと！', explain: '「季節」→ きせつ' },
        { q: '「観察」の読み方は？', opts: ['かんさつ','かんしょう','かんそう','かんけい'], correct: 0, hint: 'じっくり 見ること！', explain: '「観察」→ かんさつ' },
        { q: '「類義語」の 意味は？', opts: ['反対の意味の語','似た意味の語','同じ読みの語','別の品詞'], correct: 1, hint: '「うれしい」と「よろこぶ」は？', explain: '類義語=似た意味を持つ言葉' },
        { q: '漢字の「部首」の 役割は？', opts: ['意味のヒント','読み方を決める','書き順を示す','画数を増やす'], correct: 0, hint: '「水」偏は 水に 関係！', explain: '部首は漢字の意味の分類や意味のヒントになる' },
        { q: '「文章の主語」とは？', opts: ['動作の内容','何が・誰がにあたる部分','時間を表す','場所を表す'], correct: 1, hint: '「〇〇が（は）～する」の〇〇！', explain: '主語=「何が/誰が」に当たる文の主役部分' },
        { q: '「接続詞」の 例は？', opts: ['走る','きれい','しかし','ねこ'], correct: 2, hint: '文と文を つなぐ ことば！', explain: '接続詞=「しかし・だから・また・そして」など' },
        { q: '「同訓異字」の 例は？', opts: ['熱い・暑い','美しい・きれい','海・川','走る・歩く'], correct: 0, hint: '読み方が 同じで 字が 違う！', explain: '「熱い（あつい）」と「暑い（あつい）」は同訓異字' },
        { q: '日記の 書き方で 大切なのは？', opts: ['他の人のことだけ書く','その日の出来事や気持ちを書く','むずかしい言葉を使う','長くても短くてもよい'], correct: 1, hint: '自分が 体験したことを 書くよ！', explain: '日記は自分の体験・出来事・気持ちを書くもの' },
        { q: '「対義語」の 例は？', opts: ['美しい・きれい','賛成・反対','速い・速やか','大きい・でかい'], correct: 1, hint: '反対の意味！', explain: '「賛成」と「反対」は対義語（反対の意味）' },
        { q: '「接頭語」の 例は？', opts: ['〜的','〜化','お〜','〜性'], correct: 2, hint: '言葉の 前に つく！', explain: '「お〜」（お手紙・お菓子）は接頭語。語の前につく形式' },
        { q: '「複合語」の 例は？', opts: ['走る','美しい','飛び込む','のに'], correct: 2, hint: '二つの語が 合わさった！', explain: '「飛び込む」=「飛ぶ」+「込む」の複合動詞' },
        { q: '「擬音語」の 例は？', opts: ['きらきら','ふわふわ','ドカーン','うれしい'], correct: 2, hint: '音を 表す 言葉！', explain: '「ドカーン」は音を言葉で表した擬音語（オノマトペ）' },
        { q: '日本語の 五十音は 何行？', opts: ['5行','10行','46行','50行'], correct: 1, hint: 'あ・か・さ・た・な・は・ま・や・ら・わ行！', explain: '五十音表は10行（あ行〜わ行）' },
        { q: '「文章の主語」とは？', opts: ['動作の内容','何が・誰がにあたる部分','時間を表す','場所を表す'], correct: 1, hint: '「〇〇が（は）～する」の〇〇！', explain: '主語=「何が/誰が」に当たる文の主役部分' },
        { type:'truefalse', q:'「承」は 四字熟語「起承転結」の 2番目　ただしい？', opts:['○','×'], correct:0, hint:'起→○→転→結！', explain:'起承転結の2番目は「承」 せいかい！' },
        { type:'truefalse', q:'「擬態語」は 音を 表す ことばである　ただしい？', opts:['○','×'], correct:1, hint:'擬音語と 擬態語は ちがう！', explain:'擬態語は様子・動きを表す言葉（ふわふわ・きらきらなど）。音を表すのは擬音語' },
        { type:'truefalse', q:'「同訓異字」の 例は「熱い」と「暑い」　ただしい？', opts:['○','×'], correct:0, hint:'読み方が 同じで 字が 違う！', explain:'どちらも「あつい」と読む同訓異字 せいかい！' },
        { type:'truefalse', q:'「類義語」は 反対の 意味を もつ 語である　ただしい？', opts:['○','×'], correct:1, hint:'似た意味？ 反対の意味？', explain:'類義語は似た意味の語です（反対語は対義語）' },
      ],
      grade5: [
        { q: '「象徴」の 読み方は？', opts: ['しょうちょう','しょうてん','さんちょう','えんちょう'], correct: 0, hint: '「シンボル」のこと！', explain: '「象徴」→ しょうちょう。何かを代表する意味' },
        { q: '「比喩」の 説明として 正しいのは？', opts: ['物事を直接説明する','物事を別のものにたとえる','反対のことを言う','音を言葉で表す'], correct: 1, hint: '「雲のような やわらかい 声」は？', explain: '比喩=ある物事を別のものにたとえる表現' },
        { q: '「尊敬語」の 例は？', opts: ['いただく','おっしゃる','参る','申す'], correct: 1, hint: '相手の 動作を 高める言葉！', explain: '「おっしゃる」は「言う」の尊敬語。「いただく」は謙譲語' },
        { q: '「謙譲語」の 例は？', opts: ['いらっしゃる','召し上がる','いただく','なさる'], correct: 2, hint: '自分を へりくだる 言葉！', explain: '「いただく」は「もらう・食べる」の謙譲語' },
        { q: '「体言止め」とは？', opts: ['動詞で文を終える','名詞で文を終える','形容詞で文を終える','助詞で文を終える'], correct: 1, hint: '「輝く 星。」のように 名詞で終わる！', explain: '体言止め=名詞（体言）で文・句を終わらせる表現技法' },
        { q: '「起承転結」の「転」は 何をする？', opts: ['話題を始める','前の内容を発展させる','内容を大きく変える','まとめる'], correct: 2, hint: '四コマ漫画の 3コマ目！', explain: '「転」=それまでの流れを転換・変化させる部分' },
        { q: '次のうち 熟語の 構成で「主語+述語」は？', opts: ['登山','読書','日没','往復'], correct: 2, hint: '「日が 没する」で 文になる！', explain: '「日没」=「日が没する」（主語+述語）' },
        { q: '「反語」の 説明は？', opts: ['反対の意味の語','疑問の形で断定する表現','二つの文をつなぐ語','音を文字で表す'], correct: 1, hint: '「そんなことが できる？（→できない）」', explain: '反語=疑問形で強く肯定/否定を表す表現' },
        { q: '「受け身」の 文は？', opts: ['私は犬を見た','犬に私は見られた','犬を見ている','犬が走る'], correct: 1, hint: '「〜られる・〜される」！', explain: '「犬に私は見られた」が受け身文。〜られる・〜されるを使う' },
        { q: '「倒置法」とは？', opts: ['順番通りに書く','語順を逆にして強調する','短くまとめる','繰り返す'], correct: 1, hint: '普通と 逆の 順番！', explain: '倒置法=語順を逆にして強調する表現技法（例：美しい、この花は）' },
        { q: '「文語」と「口語」の 違いは？', opts: ['書き言葉と話し言葉の違い','地域による言葉の違い','時代の変化','方言と共通語の違い'], correct: 0, hint: '書き言葉と 話し言葉！', explain: '文語=書き言葉（古典）、口語=話し言葉（現代語）' },
        { q: '「呼応（こおう）表現」の 例は？', opts: ['大きな声で話す','決して〜ない','急いで走る','静かに座る'], correct: 1, hint: '「決して」には「〜ない」がくる！', explain: '「決して〜ない」のように特定の語と呼応する表現' },
        { type:'truefalse', q:'「擬人法」とは 人でないものを 人のように 表す 表現　ただしい？', opts:['○','×'], correct:0, hint:'「花が笑う」「風が語る」など！', explain:'擬人法=人でないものを人に例える表現 せいかい！' },
        { type:'truefalse', q:'「行間を 読む」とは 文章の 表面的な 意味だけを 読む　ただしい？', opts:['○','×'], correct:1, hint:'書かれていない ことを 読む！', explain:'「行間を読む」=書かれていない意図・感情を読み取ること' },
        { type:'truefalse', q:'「体言止め」は 名詞で 文を 終える 表現　ただしい？', opts:['○','×'], correct:0, hint:'「輝く 星。」のように！', explain:'体言止め=名詞（体言）で文・句を終わらせる表現技法 せいかい！' },
      ],
      grade6: [
        { q: '「竹取物語」の 主人公は？', opts: ['かぐや姫','浦島太郎','桃太郎','一寸法師'], correct: 0, hint: '竹の中から 生まれた！', explain: '「竹取物語」はかぐや姫の物語。日本最古の物語とも言われる' },
        { q: '「枕草子」を 書いたのは？', opts: ['紫式部','清少納言','与謝野晶子','樋口一葉'], correct: 1, hint: '「春は あけぼの」で 始まる！', explain: '枕草子は清少納言が書いた随筆（エッセイ）' },
        { q: '「故事成語」の「矛盾」の 意味は？', opts: ['力が強いこと','二つのことが食い違うこと','忙しいこと','早いこと'], correct: 1, hint: '何でも 突き通す矛と 何でも 防ぐ盾の 話！', explain: '矛盾=言っていることとやっていることが合わないこと' },
        { q: '「五・七・五」の リズムを 持つ 詩は？', opts: ['短歌','俳句','詩','物語'], correct: 1, hint: '季語が 必要な 詩！', explain: '俳句は五・七・五の17音で、季語を含む詩の形式' },
        { q: '「五・七・五・七・七」の リズムを 持つのは？', opts: ['俳句','詩','短歌','長歌'], correct: 2, hint: '31文字の 詩！', explain: '短歌は五・七・五・七・七の31音の詩' },
        { q: '「丁寧語」の 例は？', opts: ['おっしゃる','いただく','ございます','なさる'], correct: 2, hint: '「です・ます・ございます」は？', explain: '丁寧語=「です・ます・ございます」などで丁寧に話す表現' },
        { q: '「慣用句」の「手を焼く」の 意味は？', opts: ['料理をする','あつかいに困る','努力する','助ける'], correct: 1, hint: '扱いにくいものに 困る！', explain: '「手を焼く」=あつかいに困る・難儀する' },
        { q: '古文「あはれなり」の 現代語訳は？', opts: ['恐ろしい','おかしい','しみじみと感動的だ','明るい'], correct: 2, hint: '「あわれ（哀れ）」に 通じるよ！', explain: '「あはれなり」=しみじみとした感動・趣深い気持ち' },
        { q: '「平家物語」の 書き出しは？', opts: ['春はあけぼの','祇園精舎の鐘の声','昔々あるところに','月日は百代の過客'], correct: 1, hint: '平家の 栄枯盛衰！', explain: '「祇園精舎の鐘の声、諸行無常の響きあり」が平家物語の書き出し' },
        { q: '「奥の細道」を 書いたのは？', opts: ['清少納言','紫式部','松尾芭蕉','与謝蕪村'], correct: 2, hint: '俳句の 神様！', explain: '「奥の細道」は松尾芭蕉の俳諧紀行文' },
        { q: '「夏目漱石」が 書いた 作品は？', opts: ['坊っちゃん','銀河鉄道の夜','走れメロス','蜘蛛の糸'], correct: 0, hint: '「坊っちゃん」「吾輩は猫である」！', explain: '「坊っちゃん」は夏目漱石の代表作' },
        { q: '古語「をかし」の 意味は？', opts: ['かなしい','おそろしい','趣がある・おもしろい','さびしい'], correct: 2, hint: '枕草子では「をかし」が よく 登場！', explain: '「をかし」=趣がある・興味深い・おもしろい（清少納言が好んで使った）' },
        { q: '「語源」とは？', opts: ['言葉の長さ','言葉の起源・由来','言葉の音','言葉の意味の反対'], correct: 1, hint: '言葉が 生まれた 由来！', explain: '語源=言葉がどのように生まれたかの由来・起源' },
        { type:'truefalse', q:'俳句には 必ず 季語が 必要　ただしい？', opts:['○','×'], correct:0, hint:'季節を 表す 言葉！', explain:'俳句には季語（季節を表す言葉）が必要 せいかい！' },
        { type:'truefalse', q:'「万葉集」は 奈良時代に 編まれた 和歌集　ただしい？', opts:['○','×'], correct:0, hint:'日本 最古の 和歌集！', explain:'万葉集は奈良時代に編まれた現存最古の和歌集 せいかい！' },
      ],
    }
  },
  english: {
    name: 'えいごの むら',
    color: '#4488FF',
    portalColor: 0x4488FF,
    grades: {
      grade2: [
        { q: '「赤」は えいごで？', opts: ['Blue','Red','Green','Yellow'], correct: 1, hint: 'レッドストーンの いろ！', explain: 'Red=赤' },
        { q: '「ねこ」は えいごで？', opts: ['Dog','Cat','Pig','Bird'], correct: 1, hint: 'ニャーと なくよ！', explain: 'Cat=ねこ' },
        { q: '「おはよう」は えいごで？', opts: ['Good night','Good morning','Good bye','Hello'], correct: 1, hint: 'あさの あいさつ！', explain: 'Good morning=おはよう' },
        { q: '「1」は えいごで？', opts: ['Two','Three','One','Four'], correct: 2, hint: 'ワン！', explain: 'One=1' },
        { q: '「ありがとう」は えいごで？', opts: ['Sorry','Hello','Thank you','Please'], correct: 2, hint: 'サンキュー！', explain: 'Thank you=ありがとう' },
        { q: '「りんご」は えいごで？', opts: ['Banana','Apple','Orange','Grape'], correct: 1, hint: 'ア○○ル！', explain: 'Apple=りんご' },
        { q: '「あお」は えいごで？', opts: ['Red','Yellow','Blue','Green'], correct: 2, hint: 'ダイヤモンドの いろ！', explain: 'Blue=あお' },
        { q: '「いぬ」は えいごで？', opts: ['Cat','Dog','Pig','Cow'], correct: 1, hint: 'ワンワン！', explain: 'Dog=いぬ' },
        { q: '「10」は えいごで？', opts: ['Eight','Nine','Ten','Eleven'], correct: 2, hint: 'テン！', explain: 'Ten=10' },
        { type:'truefalse', q:'"Dog" は「いぬ」のこと　ただしい？', opts:['○','×'], correct:0, hint:'ワンワンと なくよ！', explain:'Dog=いぬ せいかい！' },
        { type:'truefalse', q:'"Cat" は「とり」のこと　ただしい？', opts:['○','×'], correct:1, hint:'ニャーと なくよ！', explain:'Cat=ねこ です' },
        { type:'truefalse', q:'"Good morning" は「おはよう」のこと　ただしい？', opts:['○','×'], correct:0, hint:'あさの あいさつ！', explain:'Good morning=おはよう せいかい！' },
        { q: '「みどり」は えいごで？', opts: ['Blue','Yellow','Green','White'], correct: 2, hint: 'クリーパーの いろ！', explain: 'Green=みどり' },
        { q: '「くろ」は えいごで？', opts: ['White','Gray','Black','Brown'], correct: 2, hint: 'よるの いろ！', explain: 'Black=くろ' },
        { q: '「2」は えいごで？', opts: ['One','Two','Three','Four'], correct: 1, hint: 'ツー！', explain: 'Two=2' },
        { q: '「おやすみ」は えいごで？', opts: ['Good morning','Good afternoon','Good night','Good bye'], correct: 2, hint: 'ねる まえの あいさつ！', explain: 'Good night=おやすみ' },
        { q: '「くだもの」は えいごで？', opts: ['Vegetable','Fruit','Food','Drink'], correct: 1, hint: 'フルーツ！', explain: 'Fruit=くだもの' },
        { q: '「白」は えいごで？', opts: ['Black','Gray','Yellow','White'], correct: 3, hint: '雪の いろ！', explain: 'White=白' },
        { q: '「5」は えいごで？', opts: ['Three','Four','Five','Six'], correct: 2, hint: 'ファイブ！', explain: 'Five=5' },
        { type:'truefalse', q:'"Red" は「あか」のこと　ただしい？', opts:['○','×'], correct:0, hint:'レッドストーンの いろ！', explain:'Red=あか せいかい！' },
        { type:'truefalse', q:'"Good night" は「おはよう」のこと　ただしい？', opts:['○','×'], correct:1, hint:'ないとは よる！', explain:'"Good night"=おやすみ です' },
        { type:'truefalse', q:'"Apple" は「りんご」のこと　ただしい？', opts:['○','×'], correct:0, hint:'ア○○ル！', explain:'Apple=りんご せいかい！' },
      ],
      grade3: [
        { q: '「緑」は えいごで？', opts: ['Green','Blue','Brown','White'], correct: 0, hint: 'クリーパーの いろ！', explain: 'Green=緑' },
        { q: '「ぶた」は えいごで？', opts: ['Pig','Dog','Cow','Sheep'], correct: 0, hint: 'ぶひー！', explain: 'Pig=ぶた' },
        { q: '「うし」は えいごで？', opts: ['Horse','Sheep','Cow','Chicken'], correct: 2, hint: 'ミルクを くれるよ！', explain: 'Cow=うし' },
        { q: '「ひつじ」は えいごで？', opts: ['Sheep','Goat','Pig','Rabbit'], correct: 0, hint: 'ウールを くれる どうぶつ！', explain: 'Sheep=ひつじ' },
        { q: '「I like cats.」の いみは？', opts: ['ねこが すきです','ねこが います','ねこが ほしい','ねこは おおきい'], correct: 0, hint: 'like = すき！', explain: 'I like cats.=わたしはねこがすきです' },
        { q: '「How are you?」の いみは？', opts: ['あなたは だれ？','げんきですか？','なんさいですか？','どこに いますか？'], correct: 1, hint: 'あいさつの ことば！', explain: 'How are you?=元気ですか？' },
        { q: '「黄色」は えいごで？', opts: ['Orange','Gold','Yellow','White'], correct: 2, hint: 'きんの インゴットの いろ！', explain: 'Yellow=黄色' },
        { q: '「月曜日」は えいごで？', opts: ['Sunday','Saturday','Monday','Tuesday'], correct: 2, hint: 'Mo○○ay！', explain: 'Monday=月曜日' },
        { type:'truefalse', q:'"I like cats." は「ねこが いる」という意味　ただしい？', opts:['○','×'], correct:1, hint:'like = すき！', explain:'"I like cats."=わたしはねこがすきです' },
        { type:'truefalse', q:'"How are you?" は「げんきですか？」という意味　ただしい？', opts:['○','×'], correct:0, hint:'あいさつの ことば！', explain:'How are you?=元気ですか？ せいかい！' },
        { type:'truefalse', q:'"Pig" は「ひつじ」のこと　ただしい？', opts:['○','×'], correct:1, hint:'ぶひー！', explain:'Pig=ぶた、Sheep=ひつじ です' },
        { q: '「木曜日」は えいごで？', opts: ['Wednesday','Thursday','Friday','Tuesday'], correct: 1, hint: 'サー（Thor）のひ！', explain: 'Thursday=木曜日' },
        { q: '「水曜日」は えいごで？', opts: ['Tuesday','Wednesday','Thursday','Friday'], correct: 1, hint: 'Wednesdayはw！', explain: 'Wednesday=水曜日' },
        { q: '「春」は えいごで？', opts: ['Summer','Autumn','Winter','Spring'], correct: 3, hint: 'スプリング！', explain: 'Spring=春' },
        { q: '「I have a cat.」の 意味は？', opts: ['ねこがすきです','ねこがいます（かっています）','ねこをみた','ねこがほしい'], correct: 1, hint: 'have=もっている・かっている！', explain: 'I have a cat.=私はねこをかっています' },
        { q: '「What\'s your name?」の 意味は？', opts: ['おなまえは？','おげんきですか？','なんさいですか？','どこにいますか？'], correct: 0, hint: 'name=なまえ！', explain: '"What\'s your name?"=おなまえはなんですか？' },
        { q: '「大きい」は えいごで？', opts: ['Small','Tall','Big','Long'], correct: 2, hint: 'ビッグ！', explain: 'Big=大きい' },
        { q: '「火曜日」は えいごで？', opts: ['Monday','Tuesday','Wednesday','Thursday'], correct: 1, hint: 'ツーズデー！', explain: 'Tuesday=火曜日' },
        { type:'truefalse', q:'"Spring" は「春」のこと　ただしい？', opts:['○','×'], correct:0, hint:'スプリング！', explain:'Spring=春 せいかい！' },
        { type:'truefalse', q:'"Monday" は「火曜日」のこと　ただしい？', opts:['○','×'], correct:1, hint:'Monは月のモン！', explain:'Monday=月曜日 です' },
        { type:'truefalse', q:'"Big" は「大きい」という 意味　ただしい？', opts:['○','×'], correct:0, hint:'ビッグ！', explain:'Big=大きい せいかい！' },
      ],
      grade4: [
        { q: '「This is a pen.」の 意味は？', opts: ['これはえんぴつです','これはペンです','あれはペンです','ペンが好きです'], correct: 1, hint: 'This=これ、pen=ペン！', explain: 'This is a pen.=これはペンです' },
        { q: '「I have a dog.」の 意味は？', opts: ['犬がいます','犬がすきです','わたしは犬をかっています','犬がほしいです'], correct: 2, hint: 'have=もっている・かっている', explain: 'I have a dog.=わたしは犬を飼っています' },
        { q: '「He」は だれ？', opts: ['わたし','あなた','かれ','かのじょ'], correct: 2, hint: 'She は彼女、He は？', explain: 'He=かれ She=かのじょ I=わたし You=あなた' },
        { q: '「Do you like pizza?」の 答えは？', opts: ['Yes, I am.','Yes, I do.','Yes, I have.','Yes, I like.'], correct: 1, hint: 'Do you〜?には I do！', explain: 'Do you〜?に対してYes, I do.と答える' },
        { q: '「Spring Summer Autumn Winter」は？', opts: ['曜日','つき','季節','数字'], correct: 2, hint: '春・夏・秋・冬！', explain: 'Spring=春 Summer=夏 Autumn=秋 Winter=冬（季節）' },
        { q: '「Where」は 何を 聞く 言葉？', opts: ['いつ','どこ','だれ','なに'], correct: 1, hint: '「ウェア」=「どこ」！', explain: 'Where=どこ。「Where is the school?」=学校はどこですか？' },
        { q: '「What time is it?」の 意味は？', opts: ['今日は何日？','今は何時？','どこにいますか？','天気はどう？'], correct: 1, hint: 'time=時間！', explain: 'What time is it?=今は何時ですか？' },
        { q: '「She」は だれ？', opts: ['わたし','あなた','かれ','かのじょ'], correct: 3, hint: 'He は彼、She は？', explain: 'She=かのじょ。He=かれ、I=わたし、You=あなた' },
        { q: '「I am a student.」の 意味は？', opts: ['私は学生が好きです','私は学生です','私は学生ではありません','あなたは学生です'], correct: 1, hint: 'am=です！', explain: 'I am a student.=私は学生です' },
        { q: '「What」は 何を 聞く？', opts: ['いつ','どこ','なに','だれ'], correct: 2, hint: '「ワット」=「なに」！', explain: 'What=なに。「What is this?」=これは何ですか？' },
        { q: '「I don\'t like spiders.」の 意味は？', opts: ['私はクモが好きです','私はクモが好きではない','クモを見ました','クモがいます'], correct: 1, hint: 'don\'t=しない！', explain: 'I don\'t like spiders.=私はクモが好きではない' },
        { q: '「How many」は 何を 聞く？', opts: ['値段','色','数','大きさ'], correct: 2, hint: 'How many cats?=ねこは 何匹？', explain: 'How many=いくつ（数を聞く）。How much=いくら（値段）' },
        { q: '「This is my book.」の「my」は？', opts: ['私を','私の','私は','私に'], correct: 1, hint: 'my=私の！', explain: 'my=私の（所有格）。「これは私の本です」' },
        { type:'truefalse', q:'"Who" は「だれ」を きく ことば　ただしい？', opts:['○','×'], correct:0, hint:'フー！', explain:'"Who"=だれ。「Who are you?」=あなたはだれですか？ せいかい！' },
        { type:'truefalse', q:'"She is a teacher." は「彼女は先生ではない」という意味　ただしい？', opts:['○','×'], correct:1, hint:'is=〜です！', explain:'"She is a teacher."=彼女は先生です（「ではない」ではない）' },
      ],
      grade5: [
        { q: '「I played soccer yesterday.」の 意味は？', opts: ['私はサッカーがすきです','私は昨日サッカーをしました','私はサッカーをしています','私はサッカーをします'], correct: 1, hint: 'played は play の 過去形！', explain: 'played=〜した（過去）yesterday=昨日' },
        { q: '「She can swim.」の 意味は？', opts: ['彼女は泳ぎたい','彼女は泳いでいる','彼女は泳ぐことができる','彼女は泳げない'], correct: 2, hint: 'can=〜できる！', explain: 'can=することができる。She can swim.=彼女は泳げます' },
        { q: '「I cannot run.」= 「I _____ run.」', opts: ['can\'t','don\'t','won\'t','didn\'t'], correct: 0, hint: 'cannot の 短縮形は？', explain: 'cannot=can\'t（カン\'ト）。I can\'t run.=私は走れません' },
        { q: '「He is taller than me.」の 意味は？', opts: ['彼は私より背が低い','彼は私より背が高い','私たちは同じ身長','彼は私と同じ'], correct: 1, hint: 'taller=より背が高い', explain: 'taller than=〜より背が高い（比較級）' },
        { q: '「When」は 何を 聞く 言葉？', opts: ['どこ','だれ','いつ','なに'], correct: 2, hint: '「ウェン」=「いつ」！', explain: 'When=いつ。「When is your birthday?」=誕生日はいつ？' },
        { q: '「What do you want to be?」の 意味は？', opts: ['今、何をしていますか？','何になりたいですか？','好きな食べ物は何？','何を持っていますか？'], correct: 1, hint: 'want to be=〜になりたい！', explain: 'What do you want to be?=将来何になりたいですか？' },
        { q: '英語で「月曜〜日曜」を 順に 並べると 最初は？', opts: ['Monday','Sunday','Saturday','Tuesday'], correct: 1, hint: '英語では 日曜日が 1週間の 始まり！', explain: '英語カレンダーはSunday（日）が最初。Monday〜Saturdayへ続く' },
        { q: '「I went to school.」で went は 何の 過去形？', opts: ['go','get','give','grow'], correct: 0, hint: 'go(行く)の 不規則 変化！', explain: 'go→went（不規則変化）。I went=私は行った' },
        { q: '「She likes music.」の 意味は？', opts: ['彼女は音楽が好きではない','彼女は音楽が好きだ','私は音楽が好きだ','音楽を聴いています'], correct: 1, hint: 'likes=好き！（三単現のs）', explain: 'She likes music.=彼女は音楽が好きです' },
        { q: '「比較級」の 作り方（短い語）は？', opts: ['erをつける','estをつける','moreをつける','mostをつける'], correct: 0, hint: 'tall→taller！', explain: '短い形容詞の比較級は〜er（tall→taller、fast→faster）' },
        { q: '「未来形」を 表す のは？', opts: ['am/is/are','was/were','will','have/has'], correct: 2, hint: 'will=〜するだろう！', explain: 'willが未来形を表す。「I will go」=私は行くだろう' },
        { q: '「How often」は 何を 聞く？', opts: ['どのくらいの頻度','どのくらい遠い','いくら','だれが'], correct: 0, hint: 'often=しばしば！', explain: 'How often=どのくらいの頻度・何回' },
        { type:'truefalse', q:'"He doesn\'t like vegetables." は「彼は野菜が嫌い」という意味　ただしい？', opts:['○','×'], correct:0, hint:'doesn\'t=しない！', explain:'"He doesn\'t like vegetables."=彼は野菜が好きではない せいかい！' },
        { type:'truefalse', q:'"went" は "go" の 過去形　ただしい？', opts:['○','×'], correct:0, hint:'不規則変化！', explain:'"went"は"go"の過去形（不規則変化） せいかい！' },
        { type:'truefalse', q:'英語では 最初の 文字を 大文字で 書く　ただしい？', opts:['○','×'], correct:0, hint:'文の はじまり！', explain:'英語では文の最初の文字は大文字で書く せいかい！' },
      ],
      grade6: [
        { q: '「I will go to Tokyo.」の 意味は？', opts: ['私は東京に行きました','私は東京に行きます（未来）','私は東京にいます','私は東京が好きです'], correct: 1, hint: 'will=〜するつもりだ（未来）！', explain: 'will=未来形。I will go=私は行くつもりです' },
        { q: '「He has been to America.」の 意味は？', opts: ['彼は今アメリカにいる','彼はアメリカに行ったことがある','彼はアメリカに行く','彼はアメリカが好き'], correct: 1, hint: 'has been to=〜に行ったことがある！', explain: '現在完了形（経験）。has been to=〜へ行ったことがある' },
        { q: '「The book was written by her.」は 何文？', opts: ['能動文','受動文（受け身）','疑問文','命令文'], correct: 1, hint: 'was written=書かれた（受け身）', explain: '受動態（受け身）。be動詞+過去分詞で「〜される・された」' },
        { q: '「How long」は 何を 聞く？', opts: ['どのくらいの長さ・時間','いくつ','どのように','どれほど重い'], correct: 0, hint: 'long=長さ・時間！', explain: 'How long=どのくらいの長さ/時間。「How long does it take?」' },
        { q: '「I think that she is kind.」で that 以下は？', opts: ['主語','目的語（that節）','補語','動詞'], correct: 1, hint: 'I think の 内容を 伝える！', explain: 'that節=「〜ということ」を表す名詞節で目的語になる' },
        { q: '「Can you help me?」への 正しい 返答は？', opts: ['Yes, I do.','Sure! / Of course!','Yes, I am.','No, I don\'t.'], correct: 1, hint: '「もちろん！」は 英語で？', explain: 'Sure! / Of course!（もちろん！）が自然な返答' },
        { q: '「Let\'s play basketball!」の 意味は？', opts: ['バスケをしたい','バスケをしよう！','バスケをする','バスケが好き'], correct: 1, hint: 'Let\'s=〜しよう！', explain: 'Let\'s=〜しましょう・しよう（勧誘）' },
        { q: '英語の アルファベットは 何文字？', opts: ['24文字','25文字','26文字','27文字'], correct: 2, hint: 'A〜Zまで 数えよう！', explain: 'A〜Z、a〜zの26文字。大文字・小文字がある' },
        { q: '「現在完了形」で 「経験」を 表すのは？', opts: ['have gone','have been to','went to','was going'], correct: 1, hint: '「〜したことがある」！', explain: 'have been to〜=〜へ行ったことがある（経験）' },
        { q: '「受動態」の 形は？', opts: ['be動詞+原形','be動詞+過去分詞','have+過去分詞','will+原形'], correct: 1, hint: '〜される・された！', explain: '受動態=be動詞+過去分詞「The book was written.」' },
        { q: '「I wish I could fly.」の 意味は？', opts: ['私は飛べる','私は飛びたい','飛べたらいいのに','私は飛んだ'], correct: 2, hint: 'wish+過去形=仮定法！', explain: '「I wish I could〜」=〜できたらいいのに（仮定法過去）' },
        { q: '「副詞」の 例は？', opts: ['beautiful','quickly','beauty','quick'], correct: 1, hint: '動詞や 形容詞を 修飾する！', explain: '「quickly（素早く）」は動詞を修飾する副詞（-lyが多い）' },
        { type:'truefalse', q:'"If it rains, I will stay home." は「もし雨なら 家にいる」という意味　ただしい？', opts:['○','×'], correct:0, hint:'if=もし！', explain:'"If it rains, I will stay home."=もし雨なら家にいます せいかい！' },
        { type:'truefalse', q:'英語では 文末に "." を つけず "。" を 使う　ただしい？', opts:['○','×'], correct:1, hint:'英語と 日本語の 句読点！', explain:'英語では"."（ピリオド）を使います。"。"は日本語の句点' },
        { type:'truefalse', q:'「関係代名詞 that」は 名詞を 修飾する　ただしい？', opts:['○','×'], correct:0, hint:'「私が見た男の子」→ the boy that I saw！', explain:'「that」が名詞を修飾する関係代名詞 せいかい！' },
      ],
    }
  },
};
