// quiz-data.js - クイズデータ
const QUIZ_DATA = {
  math: {
    name: 'さんすうの どうくつ',
    color: '#FF6600',
    portalColor: 0xFF6600,
    grades: {
      grade2: [
        { q: '32 + 15 = ?', opts: ['47','45','57','43'], correct: 0, hint: 'じゅうのくらいと いちのくらいに わけよう！', explain: '32+15=47' },
        { q: '21 + 36 = ?', opts: ['57','55','67','53'], correct: 0, hint: 'くらいごとに たそう！', explain: '21+36=57' },
        { q: '48 + 23 = ?', opts: ['61','71','68','65'], correct: 1, hint: 'くりあがりに ちゅうい！', explain: '48+23=71（8+3=11 くりあがり）' },
        { q: '75 - 32 = ?', opts: ['43','33','47','41'], correct: 0, hint: 'くらいごとに ひこう！', explain: '75-32=43' },
        { q: '53 - 28 = ?', opts: ['25','35','23','27'], correct: 0, hint: 'くりさがりに ちゅうい！', explain: '53-28=25' },
        { q: '2 × 3 = ?', opts: ['5','6','8','4'], correct: 1, hint: 'に さん は？', explain: '2×3=6（に さん が ろく）' },
        { q: '3 × 4 = ?', opts: ['7','10','12','9'], correct: 2, hint: 'さん し は？', explain: '3×4=12（さん し じゅうに）' },
        { q: '5 × 6 = ?', opts: ['25','30','35','28'], correct: 1, hint: 'ご ろく は？', explain: '5×6=30（ご ろく さんじゅう）' },
        { q: '4 × 7 = ?', opts: ['24','28','32','21'], correct: 1, hint: 'し しち は？', explain: '4×7=28（し しち にじゅうはち）' },
        { q: '1時間 = なん分？', opts: ['30分','50分','60分','100分'], correct: 2, hint: '時計が 1周で！', explain: '1時間=60分' },
        { q: '1cm = なんmm？', opts: ['5mm','10mm','20mm','100mm'], correct: 1, hint: '10のメモリで 1cm！', explain: '1cm=10mm' },
        { q: '三角形の 辺の数は？', opts: ['2ほん','3ほん','4ほん','5ほん'], correct: 1, hint: '「三」が ついてるよ！', explain: '三角形は辺が3本' },
      ],
      grade3: [
        { q: '125 + 68 = ?', opts: ['183','193','203','173'], correct: 1, hint: 'くりあがりに ちゅうい！', explain: '125+68=193' },
        { q: '500 - 237 = ?', opts: ['273','263','363','253'], correct: 1, hint: 'ゼロから ひくよ！', explain: '500-237=263' },
        { q: '12 ÷ 4 = ?', opts: ['2','3','4','5'], correct: 1, hint: '4のだんで 考えよう！', explain: '12÷4=3（4×3=12）' },
        { q: '24 ÷ 6 = ?', opts: ['3','4','5','6'], correct: 1, hint: '6のだんで 確認！', explain: '24÷6=4（6×4=24）' },
        { q: '7 × 8 = ?', opts: ['54','56','58','48'], correct: 1, hint: 'しち は ？', explain: '7×8=56（しち は ごじゅうろく）' },
        { q: '6 × 9 = ?', opts: ['45','54','56','63'], correct: 1, hint: 'ろく く ？', explain: '6×9=54（ろく く ごじゅうし）' },
        { q: '0.3 + 0.5 = ?', opts: ['0.7','0.8','1.0','0.9'], correct: 1, hint: '小数点を そろえよう！', explain: '0.3+0.5=0.8' },
        { q: '1m = なんcm？', opts: ['10cm','100cm','1000cm','50cm'], correct: 1, hint: 'メートルより 小さい 単位！', explain: '1m=100cm' },
        { q: '1L = なんmL？', opts: ['10mL','100mL','500mL','1000mL'], correct: 3, hint: 'ポーション なんこぶん？', explain: '1L=1000mL' },
        { q: '縦4cm 横6cmの 長方形の 面積は？', opts: ['10cm²','20cm²','24cm²','40cm²'], correct: 2, hint: 'たて × よこ！', explain: '面積=4×6=24cm²' },
      ],
      grade4: [
        { q: '1/2 + 1/4 = ?', opts: ['2/6','3/4','1/4','2/4'], correct: 1, hint: '分母を 合わせよう！', explain: '1/2=2/4、2/4+1/4=3/4' },
        { q: '3/4 - 1/8 = ?', opts: ['2/4','5/8','4/8','2/8'], correct: 1, hint: '3/4を 8分の？に 直そう！', explain: '3/4=6/8、6/8-1/8=5/8' },
        { q: '3/6 を 約分すると？', opts: ['1/2','1/3','2/3','3/3'], correct: 0, hint: '分子と 分母を 3で わろう！', explain: '3÷3=1、6÷3=2 → 1/2' },
        { q: '2.5 × 4 = ?', opts: ['8','9','10','11'], correct: 2, hint: '2.5=2+0.5に 分けよう！', explain: '2×4+0.5×4=8+2=10' },
        { q: '縦5cm 横8cmの 長方形の 面積は？', opts: ['13cm²','26cm²','40cm²','56cm²'], correct: 2, hint: 'たて × よこ！', explain: '面積=5×8=40cm²' },
        { q: '底辺8cm 高さ5cmの 三角形の 面積は？', opts: ['13cm²','20cm²','40cm²','80cm²'], correct: 1, hint: '底辺 × 高さ ÷ 2！', explain: '8×5÷2=20cm²' },
        { q: '直角は 何度？', opts: ['45度','90度','180度','360度'], correct: 1, hint: 'L字型の かど！', explain: '直角=90度' },
        { q: '三角形の 内角の和は？', opts: ['90度','180度','270度','360度'], correct: 1, hint: '3つのかどを 全部たすと？', explain: '三角形の内角の和=180度' },
        { q: '1億は 何万？', opts: ['100万','1000万','10000万','100000万'], correct: 2, hint: '0の 数を 数えよう！', explain: '1億=10000万' },
        { q: '4850を 百の位で 四捨五入すると？', opts: ['4000','4800','5000','4900'], correct: 2, hint: '百の位の数(8)は 5以上？', explain: '百の位が8（≧5）なので切り上げ → 5000' },
      ],
    }
  },
  japanese: {
    name: 'こくごの もり',
    color: '#00CC44',
    portalColor: 0x00CC44,
    grades: {
      grade2: [
        { q: '「花」の よみかたは？', opts: ['き','はな','くさ','は'], correct: 1, hint: 'きれいに さくよ！', explain: '「花」→ はな' },
        { q: '「空」の よみかたは？', opts: ['うみ','そら','やま','かわ'], correct: 1, hint: '雲が うかんでる！', explain: '「空」→ そら' },
        { q: '「石」の よみかたは？', opts: ['つち','いし','かわ','ほし'], correct: 1, hint: 'マイクラで ほれるよ！', explain: '「石」→ いし' },
        { q: '「大きい」の はんたいは？', opts: ['ひくい','ちいさい','ながい','みじかい'], correct: 1, hint: 'クリーパーは大きい、こうもりは？', explain: '「大きい」の反対は「小さい」' },
        { q: '「走る・歩く・泳ぐ」の なかまは？', opts: ['りんご','飛ぶ','赤い','きれい'], correct: 1, hint: 'からだを 動かす ことば！', explain: '走る・歩く・泳ぐ・飛ぶ はどれも動作（動詞）' },
        { q: '「とても」と 同じような 意味の ことばは？', opts: ['すこし','たいへん','あまり','ちょっと'], correct: 1, hint: 'おなじ 意味の ことば！', explain: '「とても」≒「たいへん」' },
        { q: '「犬」と「猫」、五十音で 先に くるのは？', opts: ['犬（い）','猫（ね）','同じ','わからない'], correct: 0, hint: '「い」と「ね」どちらが先？', explain: '五十音順では「い」が「ね」より先に来る' },
      ],
      grade3: [
        { q: '「春」の よみかたは？', opts: ['なつ','はる','あき','ふゆ'], correct: 1, hint: 'さくらが さく きせつ！', explain: '「春」→ はる。春夏秋冬の最初。' },
        { q: '「海」の よみかたは？', opts: ['やま','かわ','うみ','もり'], correct: 2, hint: 'さかなが いる ひろいところ！', explain: '「海」→ うみ' },
        { q: '「森」は なにが たくさん？', opts: ['みず','き','いし','はな'], correct: 1, hint: '「木」が 3つ あるよ！', explain: '「森」という字は木が3つ。木がたくさんある場所。' },
        { q: '「走る」は なに？', opts: ['名詞','動詞','形容詞','接続詞'], correct: 1, hint: 'からだを うごかす ことば！', explain: '「走る」は動作を表す動詞' },
        { q: '「美しい」は なに？', opts: ['名詞','動詞','形容詞','接続詞'], correct: 2, hint: 'ようすを あらわすよ！', explain: '「美しい」はようす（状態）を表す形容詞' },
        { q: '「ねこの手も かりたい」の いみは？', opts: ['ねこが すき','とても いそがしい','ねこの あし','てが ちいさい'], correct: 1, hint: '「ねこの ても かりたい！」', explain: '「猫の手も借りたい」=とても忙しいことわざ' },
        { q: '「光」の よみかたは？', opts: ['かぜ','ひかり','おと','いろ'], correct: 1, hint: 'グロウストーンの ○○○！', explain: '「光」→ ひかり' },
        { q: '「友」の よみかたは？', opts: ['あに','いもうと','とも','おや'], correct: 2, hint: 'いっしょに あそぶ ひと！', explain: '「友」→ とも。友達。' },
        { q: '「星」の よみかたは？', opts: ['ほし','つき','そら','くも'], correct: 0, hint: 'よるに キラキラ ひかるよ！', explain: '「星」→ ほし' },
      ],
      grade4: [
        { q: '「季節」の読み方は？', opts: ['きせつ','きぶん','けしき','かんせつ'], correct: 0, hint: '春・夏・秋・冬のこと！', explain: '「季節」→ きせつ' },
        { q: '「観察」の読み方は？', opts: ['かんさつ','かんしょう','かんそう','かんけい'], correct: 0, hint: 'じっくり 見ること！', explain: '「観察」→ かんさつ' },
        { q: '「類義語」の 意味は？', opts: ['反対の意味の語','似た意味の語','同じ読みの語','別の品詞'], correct: 1, hint: '「うれしい」と「よろこぶ」は？', explain: '類義語=似た意味を持つ言葉' },
        { q: '漢字の「部首」の 役割は？', opts: ['意味のヒント','読み方を決める','書き順を示す','画数を増やす'], correct: 0, hint: '「水」偏は 水に 関係！', explain: '部首は漢字の意味の分類や意味のヒントになる' },
        { q: '「文章の主語」とは？', opts: ['動作の内容','何が・誰がにあたる部分','時間を表す','場所を表す'], correct: 1, hint: '「〇〇が（は）～する」の〇〇！', explain: '主語=「何が/誰が」に当たる文の主役部分' },
        { q: '「接続詞」の 例は？', opts: ['走る','きれい','しかし','ねこ'], correct: 2, hint: '文と文を つなぐ ことば！', explain: '接続詞=「しかし・だから・また・そして」など' },
      ],
    }
  },
  english: {
    name: 'えいごの むら',
    color: '#4488FF',
    portalColor: 0x4488FF,
    grades: {
      grade2: [
        { q: '「赤」は えいごで？', opts: ['Blue','Red','Green','Yellow'], correct: 1, hint: 'レッドストーンの いろ！', explain: 'Red=赤' },
        { q: '「ねこ」は えいごで？', opts: ['Dog','Cat','Pig','Bird'], correct: 1, hint: 'ニャーと なくよ！', explain: 'Cat=ねこ' },
        { q: '「おはよう」は えいごで？', opts: ['Good night','Good morning','Good bye','Hello'], correct: 1, hint: 'あさの あいさつ！', explain: 'Good morning=おはよう' },
        { q: '「1」は えいごで？', opts: ['Two','Three','One','Four'], correct: 2, hint: 'ワン！', explain: 'One=1' },
        { q: '「ありがとう」は えいごで？', opts: ['Sorry','Hello','Thank you','Please'], correct: 2, hint: 'サンキュー！', explain: 'Thank you=ありがとう' },
        { q: '「りんご」は えいごで？', opts: ['Banana','Apple','Orange','Grape'], correct: 1, hint: 'ア○○ル！', explain: 'Apple=りんご' },
        { q: '「あお」は えいごで？', opts: ['Red','Yellow','Blue','Green'], correct: 2, hint: 'ダイヤモンドの いろ！', explain: 'Blue=あお' },
      ],
      grade3: [
        { q: '「緑」は えいごで？', opts: ['Green','Blue','Brown','White'], correct: 0, hint: 'クリーパーの いろ！', explain: 'Green=緑' },
        { q: '「ぶた」は えいごで？', opts: ['Pig','Dog','Cow','Sheep'], correct: 0, hint: 'ぶひー！', explain: 'Pig=ぶた' },
        { q: '「うし」は えいごで？', opts: ['Horse','Sheep','Cow','Chicken'], correct: 2, hint: 'ミルクを くれるよ！', explain: 'Cow=うし' },
        { q: '「ひつじ」は えいごで？', opts: ['Sheep','Goat','Pig','Rabbit'], correct: 0, hint: 'ウールを くれる どうぶつ！', explain: 'Sheep=ひつじ' },
        { q: '「I like cats.」の いみは？', opts: ['ねこが すきです','ねこが います','ねこが ほしい','ねこは おおきい'], correct: 0, hint: 'like = すき！', explain: 'I like cats.=わたしはねこがすきです' },
        { q: '「How are you?」の いみは？', opts: ['あなたは だれ？','げんきですか？','なんさいですか？','どこに いますか？'], correct: 1, hint: 'あいさつの ことば！', explain: 'How are you?=元気ですか？' },
        { q: '「黄色」は えいごで？', opts: ['Orange','Gold','Yellow','White'], correct: 2, hint: 'きんの インゴットの いろ！', explain: 'Yellow=黄色' },
      ],
      grade4: [
        { q: '「This is a pen.」の 意味は？', opts: ['これはえんぴつです','これはペンです','あれはペンです','ペンが好きです'], correct: 1, hint: 'This=これ、pen=ペン！', explain: 'This is a pen.=これはペンです' },
        { q: '「I have a dog.」の 意味は？', opts: ['犬がいます','犬がすきです','わたしは犬をかっています','犬がほしいです'], correct: 2, hint: 'have=もっている・かっている', explain: 'I have a dog.=わたしは犬を飼っています' },
        { q: '「He」は だれ？', opts: ['わたし','あなた','かれ','かのじょ'], correct: 2, hint: 'She は彼女、He は？', explain: 'He=かれ She=かのじょ I=わたし You=あなた' },
        { q: '「月曜日」は えいごで？', opts: ['Sunday','Saturday','Monday','Tuesday'], correct: 2, hint: 'Mo○○ay！', explain: 'Monday=月曜日' },
        { q: '「Do you like pizza?」の 答えは？', opts: ['Yes, I am.','Yes, I do.','Yes, I have.','Yes, I like.'], correct: 1, hint: 'Do you〜?には I do！', explain: 'Do you〜?に対してYes, I do.と答える' },
        { q: '「Spring Summer Autumn Winter」は？', opts: ['曜日','つき','季節','数字'], correct: 2, hint: '春・夏・秋・冬！', explain: 'Spring=春 Summer=夏 Autumn=秋 Winter=冬（季節）' },
      ],
    }
  },
};
